/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

@interface _CC_MD5 (Cyte)
+ (id)stringWithUTF8Bytes:(const char *)fp8 length:(int)fp12;
+ (id)stringWithUTF8BytesNoCopy:(const char *)fp8 length:(int)fp12;
@end

