/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CydiaWebViewController.h"

@class Database;

@interface ConfirmationController : CydiaWebViewController
{
    Database *database_;
    struct MenesObjectHandle<UIAlertView, 0> essential_;
    struct MenesObjectHandle<NSDictionary, 0> changes_;
    struct MenesObjectHandle<NSMutableArray, 0> issues_;
    struct MenesObjectHandle<NSDictionary, 0> sizes_;
    BOOL substrate_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)confirmButtonClicked;
- (void)cancelButtonClicked;
- (void)applyRightButton;
- (id)leftButton;
- (id)initWithDatabase:(id)fp8;
- (void)webView:(id)fp8 didClearWindowObject:(id)fp12 forFrame:(id)fp16;
- (id)invokeDefaultMethodWithArguments:(id)fp8;
- (void)_doContinue;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)complete;

@end

