/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

@interface CydiaProgressEvent : _CC_MD5
{
    struct MenesObjectHandle<NSString, 0> message_;
    struct MenesObjectHandle<NSString, 0> type_;
    struct MenesObjectHandle<NSArray, 0> item_;
    struct MenesObjectHandle<NSString, 0> package_;
    struct MenesObjectHandle<NSString, 0> url_;
    struct MenesObjectHandle<NSString, 0> version_;
}

+ (BOOL)isKeyExcludedFromWebScript:(const char *)fp8;
+ (id)_attributeKeys;
+ (id)eventWithMessage:(id)fp8 ofType:(id)fp12 forItemDesc:(struct ItemDesc *)fp16;
+ (id)eventWithMessage:(id)fp8 ofType:(id)fp12 forPackage:(id)fp16;
+ (id)eventWithMessage:(id)fp8 ofType:(id)fp12;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)compoundTitle;
- (id)compoundMessage;
- (id)compound:(id)fp8;
- (id)version;
- (void)setVersion:(id)fp8;
- (void)setURL:(id)fp8;
- (id)url;
- (void)setPackage:(id)fp8;
- (id)package;
- (void)setItem:(id)fp8;
- (id)item;
- (id)type;
- (id)message;
- (id)initWithMessage:(id)fp8 ofType:(id)fp12;
- (id)attributeKeys;

@end

