/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CyteTabBarController.h"

#import "FetchDelegate-Protocol.h"
#import "UITabBarControllerDelegate-Protocol.h"

@class Database, NSObject<CydiaDelegate>;

@interface CydiaTabBarController : CyteTabBarController <UITabBarControllerDelegate, FetchDelegate>
{
    Database *database_;
    struct MenesObjectHandle<UIActivityIndicatorView, 0> indicator_;
    _Bool updating_;
    NSObject<CydiaDelegate> *updatedelegate_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setUpdateDelegate:(id)fp8;
- (void)stopSourceFetch:(id)fp8;
- (void)startSourceFetch:(id)fp8;
- (_Bool)isSourceCancelled;
- (BOOL)updating;
- (void)cancelPressed;
- (void)cancelUpdate;
- (void)completeUpdate;
- (void)stopUpdateWithSelector:(SEL)fp8;
- (void)performUpdate;
- (void)beginUpdate;
- (id)initWithDatabase:(id)fp8;
- (id)navigationURLCollection;

@end

