/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

@interface CydiaProgressData : _CC_MD5
{
    id delegate_;
    _Bool running_;
    float percent_;
    float current_;
    float total_;
    float speed_;
    struct MenesObjectHandle<NSMutableArray, 0> events_;
    struct MenesObjectHandle<NSString, 0> title_;
    struct MenesObjectHandle<NSString, 0> status_;
    struct MenesObjectHandle<NSString, 0> finish_;
}

+ (BOOL)isKeyExcludedFromWebScript:(const char *)fp8;
+ (id)_attributeKeys;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)running;
- (void)setRunning:(_Bool)fp8;
- (id)finish;
- (void)setFinish:(id)fp8;
- (id)title;
- (void)setTitle:(id)fp8;
- (void)addEvent:(id)fp8;
- (void)removeAllEvents;
- (id)events;
- (id)speed;
- (void)setSpeed:(float)fp8;
- (id)total;
- (void)setTotal:(float)fp8;
- (id)current;
- (void)setCurrent:(float)fp8;
- (id)percent;
- (void)setPercent:(float)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)init;
- (id)attributeKeys;

@end

