/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

#import "ConfirmationControllerDelegate-Protocol.h"
#import "CydiaDelegate-Protocol.h"
#import "DatabaseDelegate-Protocol.h"

@class Database;

@interface Cydia : _CC_MD5 <ConfirmationControllerDelegate, DatabaseDelegate, CydiaDelegate>
{
    struct MenesObjectHandle<UIWindow, 0> window_;
    struct MenesObjectHandle<CydiaTabBarController, 0> tabbar_;
    struct MenesObjectHandle<CyteTabBarController, 0> emulated_;
    struct MenesObjectHandle<AppCacheController, 0> appcache_;
    struct MenesObjectHandle<NSMutableArray, 0> essential_;
    struct MenesObjectHandle<NSMutableArray, 0> broken_;
    Database *database_;
    struct MenesObjectHandle<NSURL, 0> starturl_;
    unsigned int locked_;
    unsigned int activity_;
    struct MenesObjectHandle<StashController, 0> stash_;
    _Bool loaded_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)addProgressEventOnMainThread:(id)fp8 forTask:(id)fp12;
- (void)addProgressEventForTask:(id)fp8;
- (void)addProgressEvent:(id)fp8 forTask:(id)fp12;
- (void)showActionSheet:(id)fp8 fromItem:(id)fp12;
- (void)loadData;
- (id)defaultStartPages;
- (void)applicationDidFinishLaunching:(id)fp8;
- (void)applicationDidReceiveMemoryWarning:(id)fp8;
- (void)_sendMemoryWarningNotifications;
- (void)_sendMemoryWarningNotification;
- (void)setupViewControllers;
- (void)stash;
- (void)removeStashController;
- (void)addStashController;
- (void)setConfigurationData:(id)fp8;
- (void)applicationWillEnterForeground:(id)fp8;
- (void)applicationDidEnterBackground:(id)fp8;
- (void)applicationWillTerminate:(id)fp8;
- (void)saveState;
- (void)applicationWillResignActive:(id)fp8;
- (void)applicationOpenURL:(id)fp8;
- (BOOL)openCydiaURL:(id)fp8 forExternal:(BOOL)fp12;
- (id)pageForURL:(id)fp8 forExternal:(BOOL)fp12 withReferrer:(id)fp16;
- (id)pageForPackage:(id)fp8 withReferrer:(id)fp12;
- (void)removeProgressHUD:(id)fp8;
- (id)addProgressHUD;
- (void)_setSuspended:(BOOL)fp8;
- (void)_animateSuspension:(BOOL)fp8 duration:(double)fp12 startTime:(double)fp20 scale:(float)fp28;
- (void)applicationSuspend:(struct __GSEvent *)fp8;
- (void)applicationSuspend;
- (void)suspend;
- (void)suspendReturningToLastApp:(BOOL)fp8;
- (BOOL)isSafeToSuspend;
- (void)applicationWillSuspend;
- (void)system:(id)fp8;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)cancelAndClear:(_Bool)fp8;
- (void)releaseNetworkActivityIndicator;
- (void)retainNetworkActivityIndicator;
- (void)confirmWithNavigationController:(id)fp8;
- (void)perform_;
- (void)uicache;
- (void)_uicache;
- (void)distUpgrade;
- (void)removePackage:(id)fp8;
- (void)installPackage:(id)fp8;
- (void)installPackages:(id)fp8;
- (void)clearPackage:(id)fp8;
- (void)queue;
- (_Bool)perform;
- (void)resolve;
- (void)addTrivialSource:(id)fp8;
- (void)addSource:(id)fp8 withDistribution:(id)fp12 andSections:(id)fp16;
- (void)addSource:(id)fp8;
- (void)syncData;
- (void)reloadData;
- (void)repairWithSelector:(SEL)fp8;
- (void)repairWithInvocation:(id)fp8;
- (void)detachNewProgressSelector:(SEL)fp8 toTarget:(id)fp12 forController:(id)fp16 title:(id)fp20;
- (id)invokeNewProgress:(id)fp8 forController:(id)fp12 withTitle:(id)fp16;
- (void)presentModalViewController:(id)fp8 force:(BOOL)fp12;
- (void)disemulate;
- (void)update_;
- (void)updateDataAndLoad;
- (void)updateData;
- (void)reloadDataWithInvocation:(id)fp8;
- (void)refreshIfPossible;
- (void)_refreshIfPossible;
- (void)_updateData;
- (void)unloadData;
- (id)queueNavigationController;
- (void)_saveConfig;
- (void)reloadSpringBoard;
- (void)returnToCydia;
- (void)_loaded;
- (BOOL)updating;
- (_Bool)requestUpdate;
- (void)cancelUpdate;
- (void)beginUpdate;
- (void)unlockSuspend;
- (void)lockSuspend;

@end

