/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CydiaWebViewController.h"

#import "UIActionSheetDelegate-Protocol.h"

@class Database;

@interface CYPackageController : CydiaWebViewController <UIActionSheetDelegate>
{
    Database *database_;
    struct MenesObjectHandle<Package, 0> package_;
    struct MenesObjectHandle<NSString, 0> name_;
    _Bool commercial_;
    struct vector<std::pair<MenesObjectHandle<NSString, 0>, MenesObjectHandle<NSString, 0>>, std::allocator<std::pair<MenesObjectHandle<NSString, 0>, MenesObjectHandle<NSString, 0>>>> buttons_;
    struct MenesObjectHandle<UIBarButtonItem, 0> button_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (_Bool)isLoading;
- (void)reloadData;
- (id)initWithDatabase:(id)fp8 forPackage:(id)fp12 withReferrer:(id)fp16;
- (void)setPageColor:(id)fp8;
- (id)rightButton;
- (void)applyLoadingTitle;
- (void)reloadButtonClicked;
- (void)_customButtonClicked;
- (_Bool)_allowJavaScriptPanel;
- (void)actionSheet:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)_clickButtonWithName:(id)fp8;
- (id)navigationURL;

@end

