/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

@interface CyteTableViewCellContentView : _CC_MD5
{
    id <CyteTableViewCellDelegate> delegate_;
}

- (void)drawRect:(struct CGRect)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)initWithFrame:(struct CGRect)fp8;

@end

