/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

@interface CyteViewController : _CC_MD5
{
    id delegate_;
    BOOL loaded_;
    struct MenesObjectHandle<UIColor, 0> color_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (void)setPageColor:(id)fp8;
- (id)navigationURL;
- (void)unloadData;
- (void)reloadData;
- (void)setView:(id)fp8;
- (void)releaseSubviews;
- (BOOL)hasLoaded;
- (void)viewWillAppear:(BOOL)fp8;
- (id)delegate;
- (void)setDelegate:(id)fp8;

@end

