/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

#import "WebPolicyDecisionListener-Protocol.h"

@interface CYWebPolicyDecisionMediator : _CC_MD5 <WebPolicyDecisionListener>
{
    id <WebPolicyDecisionListener> listener_;
    int decision_;
}

- (void)use;
- (void)ignore;
- (void)download;
- (_Bool)decide;
- (_Bool)decided;
- (int)decision;
- (id)initWithListener:(id)fp8;

@end

