/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol DatabaseDelegate
- (void)addProgressEventOnMainThread:(id)fp8 forTask:(id)fp12;
- (void)setConfigurationData:(id)fp8;
- (void)repairWithSelector:(SEL)fp8;
@end

