/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PackageListController.h"

@interface FilteredPackageListController : PackageListController
{
    struct Function<bool, Package *> filter_;
    struct Function<void, NSMutableArray *> sorter_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithDatabase:(id)fp8 title:(id)fp12 filter:(struct Function<bool, Package *>)fp16;
- (id)_reloadPackages;
- (void)setSorter:(struct Function<void, NSMutableArray *>)fp8;
- (void)setFilter:(struct Function<bool, Package *>)fp8;

@end

