/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CydiaWebViewController.h"

@interface HomeController : CydiaWebViewController
{
    struct __CFRunLoop *runloop_;
    struct __SCNetworkReachability *reachability_;
}

- (id)leftButton;
- (void)aboutButtonClicked;
- (id)navigationURL;
- (void)dealloc;
- (id)init;

@end

