/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FilteredPackageListController.h"

@interface InstalledController : FilteredPackageListController
{
    _Bool sectioned_;
}

- (void)modeChanged:(id)fp8;
- (void)queueStatusDidChange;
- (void)queueButtonClicked;
- (id)initWithDatabase:(id)fp8;
- (id)sectionsForPackages:(id)fp8;
- (void)useFilter:(id)fp8;
- (void)useRecent;
- (id)navigationURL;
- (id)referrerURL;

@end

