/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CyteTableViewCell.h"

#import "CyteTableViewCellDelegate-Protocol.h"

@interface PackageCell : CyteTableViewCell <CyteTableViewCellDelegate>
{
    struct MenesObjectHandle<UIImage, 0> icon_;
    struct MenesObjectHandle<NSString, 0> name_;
    struct MenesObjectHandle<NSString, 0> description_;
    _Bool commercial_;
    struct MenesObjectHandle<NSString, 0> source_;
    struct MenesObjectHandle<UIImage, 0> badge_;
    struct MenesObjectHandle<UIImage, 0> placard_;
    _Bool summarized_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)drawContentRect:(struct CGRect)fp8;
- (void)drawNormalContentRect:(struct CGRect)fp8;
- (void)drawSummaryContentRect:(struct CGRect)fp8;
- (void)setPackage:(id)fp8 asSummary:(_Bool)fp12;
- (id)accessibilityLabel;
- (id)init;

@end

