/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CyteViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class Database;

@interface PackageSettingsController : CyteViewController <UITableViewDataSource, UITableViewDelegate>
{
    Database *database_;
    struct MenesObjectHandle<NSString, 0> name_;
    struct MenesObjectHandle<Package, 0> package_;
    struct MenesObjectHandle<UITableView, 2> table_;
    struct MenesObjectHandle<UISwitch, 0> subscribedSwitch_;
    struct MenesObjectHandle<UISwitch, 0> ignoredSwitch_;
    struct MenesObjectHandle<UITableViewCell, 0> subscribedCell_;
    struct MenesObjectHandle<UITableViewCell, 0> ignoredCell_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)reloadData;
- (id)initWithDatabase:(id)fp8 package:(id)fp12;
- (void)releaseSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)onIgnored:(id)fp8;
- (void)_updateIgnored;
- (void)onSubscribed:(id)fp8;
- (id)tableView:(id)fp8 titleForFooterInSection:(int)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)navigationURL;

@end

