/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol ProgressDelegate
- (void)setTitle:(id)fp8;
- (_Bool)isProgressCancelled;
- (void)setProgressCancellable:(id)fp8;
- (void)setProgressStatus:(id)fp8;
- (void)setProgressPercent:(id)fp8;
- (void)addProgressEvent:(id)fp8;
@end

