/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

@class NSMutableDictionary, NSOperation, NSOperationQueue, NSString, NSTimer;

@interface SDURLCache : _CC_MD5
{
    NSString *diskCachePath;
    NSMutableDictionary *diskCacheInfo;
    BOOL diskCacheInfoDirty;
    BOOL ignoreMemoryOnlyStoragePolicy;
    BOOL breakURLCacheCompatibility;
    unsigned int diskCacheUsage;
    double minCacheInterval;
    NSOperationQueue *ioQueue;
    NSTimer *periodicMaintenanceTimer;
    NSOperation *periodicMaintenanceOperation;
}

+ (id)defaultCachePath;
+ (id)expirationDateFromHeaders:(id)fp8 withStatusCode:(int)fp12;
+ (id)dateFromHttpDateString:(id)fp8;
+ (id)cacheKeyForURL:(id)fp8;
+ (id)canonicalRequestForRequest:(id)fp8;
- (void)setBreakURLCacheCompatibility:(BOOL)fp8;
- (BOOL)breakURLCacheCompatibility;
- (void)setIgnoreMemoryOnlyStoragePolicy:(BOOL)fp8;
- (BOOL)ignoreMemoryOnlyStoragePolicy;
- (void)setPeriodicMaintenanceOperation:(id)fp8;
- (id)periodicMaintenanceOperation;
- (void)setIoQueue:(id)fp8;
- (id)ioQueue;
- (void)setMinCacheInterval:(double)fp8;
- (double)minCacheInterval;
- (void)setDiskCachePath:(id)fp8;
- (void)dealloc;
- (BOOL)isCached:(id)fp8;
- (void)removeAllCachedResponses;
- (void)removeCachedResponseForRequest:(id)fp8;
- (unsigned int)currentDiskUsage;
- (id)cachedResponseForRequest:(id)fp8;
- (void)storeCachedResponse:(id)fp8 forRequest:(id)fp12;
- (id)initWithMemoryCapacity:(unsigned int)fp8 diskCapacity:(unsigned int)fp12 diskPath:(id)fp16;
- (void)logEvent:(id)fp8 forRequest:(id)fp12;
- (void)periodicMaintenance;
- (void)storeToDisk:(id)fp8;
- (void)balanceDiskUsage;
- (void)removeCachedResponseForCachedKeys:(id)fp8;
- (void)saveCacheInfo;
- (void)createDiskCachePath;
- (id)diskCachePath;
- (id)diskCacheInfo;

@end

