/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

@interface Section : _CC_MD5
{
    struct MenesObjectHandle<NSString, 0> name_;
    unsigned long row_;
    unsigned long count_;
    struct MenesObjectHandle<NSString, 0> localized_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)localized;
- (void)setCount:(unsigned long)fp8;
- (void)addToCount;
- (void)addToRow;
- (unsigned long)count;
- (unsigned long)row;
- (void)setName:(id)fp8;
- (id)name;
- (id)initWithName:(id)fp8 row:(unsigned long)fp12 localize:(BOOL)fp16;
- (id)initWithName:(id)fp8 localize:(BOOL)fp12;
- (id)initWithName:(id)fp8 localized:(id)fp12;
- (int)compareByLocalized:(id)fp8;

@end

