/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FilteredPackageListController.h"

@interface SectionController : FilteredPackageListController
{
    struct MenesObjectHandle<NSString, 0> key_;
    struct MenesObjectHandle<NSString, 0> section_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)reloadData;
- (id)initWithDatabase:(id)fp8 source:(id)fp12 section:(id)fp16;
- (id)navigationURL;
- (id)referrerURL;

@end

