/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CyteViewController.h"

@interface StashController : CyteViewController
{
    struct MenesObjectHandle<UIActivityIndicatorView, 0> spinner_;
    struct MenesObjectHandle<UILabel, 0> status_;
    struct MenesObjectHandle<UILabel, 0> caption_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)releaseSubviews;
- (void)loadView;

@end

