/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@class AppCacheController, CydiaObject, CydiaOperation, CydiaProgressData, CydiaTabBarController, CyteTabBarController, CyteTableViewCellContentView, CyteWebView, CyteWebViewController, IndirectDelegate, NSArray, NSDate, NSDictionary, NSError, NSMutableArray, NSMutableDictionary, NSMutableSet, NSObject, NSObject<ProgressDelegate>, NSString, NSTimer, NSURL, NSURLAuthenticationChallenge, NSURLRequest, Package, Source, StashController, UIActivityIndicatorView, UIAlertView, UIBarButtonItem, UIColor, UIImage, UILabel, UIProgressHUD, UISearchBar, UISwitch, UITableView, UITableViewCell, UIView, UIViewController, UIWindow, WebScriptObject;

struct Abstract;

struct CGPoint {
    float _field1;
    float _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    float _field1;
    float _field2;
};

struct CYPool {
    char *data_;
    unsigned int size_;
    struct Cleaner *cleaner_;
};

struct CYString {
    char *data_;
    unsigned int size_;
    struct __CFString *cache_;
};

struct CancelStatus {
    void **_field1;
    struct timeval _field2;
    struct timeval _field3;
    double _field4;
    double _field5;
    double _field6;
    double _field7;
    double _field8;
    unsigned long _field9;
    unsigned long _field10;
    unsigned long _field11;
    _Bool _field12;
    _Bool _field13;
    _Bool _field14;
};

struct Cleaner;

struct CydiaStatus {
    void **_vptr$pkgAcquireStatus;
    struct timeval Time;
    struct timeval StartTime;
    double LastBytes;
    double CurrentCPS;
    double CurrentBytes;
    double TotalBytes;
    double FetchedBytes;
    unsigned long ElapsedTime;
    unsigned long TotalItems;
    unsigned long CurrentItems;
    _Bool Update;
    _Bool MorePulses;
    _Bool cancelled_;
    NSObject<ProgressDelegate> *delegate_;
};

struct DepIterator {
    struct Dependency *_field1;
    int _field2;
    struct pkgCache *_field3;
};

struct Dependency;

struct FileFd {
    void **_field1;
    int _field2;
    unsigned long _field3;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field4;
};

struct Function<bool, Package *> {
    struct Abstract *abstract_;
};

struct Function<void, NSMutableArray *> {
    struct Abstract *abstract_;
};

struct Item;

struct ItemDesc {
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field1;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field2;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field3;
    struct Item *_field4;
};

struct MMap;

struct MenesObjectHandle<AppCacheController, 0> {
    AppCacheController *value_;
};

struct MenesObjectHandle<CydiaObject, 0> {
    CydiaObject *value_;
};

struct MenesObjectHandle<CydiaOperation, 0> {
    CydiaOperation *value_;
};

struct MenesObjectHandle<CydiaProgressData, 1> {
    CydiaProgressData *value_;
};

struct MenesObjectHandle<CydiaTabBarController, 0> {
    CydiaTabBarController *value_;
};

struct MenesObjectHandle<CyteTabBarController, 0> {
    CyteTabBarController *value_;
};

struct MenesObjectHandle<CyteTableViewCellContentView, 1> {
    CyteTableViewCellContentView *value_;
};

struct MenesObjectHandle<CyteWebView, 1> {
    CyteWebView *value_;
};

struct MenesObjectHandle<CyteWebViewController, 0> {
    CyteWebViewController *value_;
};

struct MenesObjectHandle<IndirectDelegate, 1> {
    IndirectDelegate *value_;
};

struct MenesObjectHandle<NSArray, 0> {
    NSArray *value_;
};

struct MenesObjectHandle<NSDate, 0> {
    NSDate *value_;
};

struct MenesObjectHandle<NSDictionary, 0> {
    NSDictionary *value_;
};

struct MenesObjectHandle<NSError, 0> {
    NSError *value_;
};

struct MenesObjectHandle<NSMutableArray, 0> {
    NSMutableArray *value_;
};

struct MenesObjectHandle<NSMutableDictionary, 0> {
    NSMutableDictionary *value_;
};

struct MenesObjectHandle<NSMutableSet, 0> {
    NSMutableSet *value_;
};

struct MenesObjectHandle<NSObject, 0> {
    NSObject *value_;
};

struct MenesObjectHandle<NSString, 0> {
    NSString *value_;
};

struct MenesObjectHandle<NSTimer, 0> {
    NSTimer *value_;
};

struct MenesObjectHandle<NSURL, 0> {
    NSURL *value_;
};

struct MenesObjectHandle<NSURLAuthenticationChallenge, 0> {
    NSURLAuthenticationChallenge *value_;
};

struct MenesObjectHandle<NSURLRequest, 0> {
    NSURLRequest *value_;
};

struct MenesObjectHandle<Package, 0> {
    Package *value_;
};

struct MenesObjectHandle<Source, 0> {
    Source *value_;
};

struct MenesObjectHandle<Source, 1> {
    Source *value_;
};

struct MenesObjectHandle<StashController, 0> {
    StashController *value_;
};

struct MenesObjectHandle<UIActivityIndicatorView, 0> {
    UIActivityIndicatorView *value_;
};

struct MenesObjectHandle<UIAlertView, 0> {
    UIAlertView *value_;
};

struct MenesObjectHandle<UIBarButtonItem, 0> {
    UIBarButtonItem *value_;
};

struct MenesObjectHandle<UIColor, 0> {
    UIColor *value_;
};

struct MenesObjectHandle<UIImage, 0> {
    UIImage *value_;
};

struct MenesObjectHandle<UILabel, 0> {
    UILabel *value_;
};

struct MenesObjectHandle<UIProgressHUD, 0> {
    UIProgressHUD *value_;
};

struct MenesObjectHandle<UISearchBar, 1> {
    UISearchBar *value_;
};

struct MenesObjectHandle<UISwitch, 0> {
    UISwitch *value_;
};

struct MenesObjectHandle<UITableView, 2> {
    UITableView *value_;
};

struct MenesObjectHandle<UITableViewCell, 0> {
    UITableViewCell *value_;
};

struct MenesObjectHandle<UIView, 0> {
    UIView *value_;
};

struct MenesObjectHandle<UIViewController, 0> {
    UIViewController *value_;
};

struct MenesObjectHandle<UIWindow, 0> {
    UIWindow *value_;
};

struct MenesObjectHandle<WebScriptObject, 0> {
    WebScriptObject *value_;
};

struct MethodConfig;

struct Offset<PackageValue> {
    unsigned int _field1;
};

struct Offset<void> {
    unsigned int _field1;
};

struct Package;

struct PackageFile;

struct PackageValue {
    struct Offset<void> _field1;
    struct Offset<PackageValue> _field2;
    unsigned int :23;
    unsigned int :1;
    unsigned int :8;
    int _field3;
    int _field4;
    unsigned short _field5;
    unsigned short _field6;
    char _field7[8];
    char _field8[0];
};

struct ParsedPackage {
    struct CYString _field1;
    struct CYString _field2;
    struct CYString _field3;
    struct CYString _field4;
    struct CYString _field5;
    struct CYString _field6;
    struct CYString _field7;
    struct CYString _field8;
};

struct Parser;

struct PkgFileIterator {
    struct pkgCache *_field1;
    struct PackageFile *_field2;
};

struct PkgIterator {
    struct Package *Pkg;
    struct pkgCache *Owner;
    long HashIndex;
};

struct Policy {
    void **_field1;
};

struct Queue;

struct RegEx {
    struct URegularExpression *regex_;
    int capture_;
    unsigned int size_;
};

struct SPtr<pkgPackageManager> {
    struct pkgPackageManager *Ptr;
};

struct URegularExpression;

struct VerFile;

struct VerFileIterator {
    struct pkgCache *Owner;
    struct VerFile *FileP;
};

struct VerIterator {
    struct Version *Ver;
    struct pkgCache *Owner;
};

struct Version;

struct Worker;

struct _Alloc_hider {
    char *_field1;
};

struct _NSZone;

struct _Rb_tree<const char *, std::pair<const char *const, MenesObjectHandle<NSString, 0>>, std::_Select1st<std::pair<const char *const, MenesObjectHandle<NSString, 0>>>, std::less<const char *>, std::allocator<std::pair<const char *const, MenesObjectHandle<NSString, 0>>>> {
    struct _Rb_tree_impl<std::less<const char *>, false> _M_impl;
};

struct _Rb_tree<std::basic_string<char>, std::basic_string<char>, std::_Identity<std::basic_string<char>>, std::less<std::basic_string<char>>, std::allocator<std::basic_string<char>>> {
    struct _Rb_tree_impl<std::less<std::basic_string<char>>, false> _M_impl;
};

struct _Rb_tree<unsigned long, std::pair<const unsigned long, MenesObjectHandle<Source, 0>>, std::_Select1st<std::pair<const unsigned long, MenesObjectHandle<Source, 0>>>, std::less<unsigned long>, std::allocator<std::pair<const unsigned long, MenesObjectHandle<Source, 0>>>> {
    struct _Rb_tree_impl<std::less<unsigned long>, false> _M_impl;
};

struct _Rb_tree_impl<std::less<const char *>, false> {
    struct less<const char *> _M_key_compare;
    struct _Rb_tree_node_base _M_header;
    unsigned int _M_node_count;
};

struct _Rb_tree_impl<std::less<std::basic_string<char>>, false> {
    struct less<std::basic_string<char>> _M_key_compare;
    struct _Rb_tree_node_base _M_header;
    unsigned int _M_node_count;
};

struct _Rb_tree_impl<std::less<unsigned long>, false> {
    struct less<unsigned long> _M_key_compare;
    struct _Rb_tree_node_base _M_header;
    unsigned int _M_node_count;
};

struct _Rb_tree_node_base {
    int _M_color;
    struct _Rb_tree_node_base *_M_parent;
    struct _Rb_tree_node_base *_M_left;
    struct _Rb_tree_node_base *_M_right;
};

struct _Vector_impl {
    struct metaIndex **_M_start;
    struct metaIndex **_M_finish;
    struct metaIndex **_M_end_of_storage;
};

struct __CFArray;

struct __CFRunLoop;

struct __CFString;

struct __GSEvent;

struct __SCNetworkReachability;

struct __sFILE {
    char *_field1;
    int _field2;
    int _field3;
    short _field4;
    short _field5;
    struct __sbuf _field6;
    int _field7;
    void *_field8;
    void *_field9;
    void *_field10;
    void *_field11;
    void *_field12;
    struct __sbuf _field13;
    struct __sFILEX *_field14;
    int _field15;
    unsigned char _field16[3];
    unsigned char _field17[1];
    struct __sbuf _field18;
    int _field19;
    long long _field20;
};

struct __sFILEX;

struct __sbuf {
    char *_field1;
    int _field2;
};

struct basic_string<char, std::char_traits<char>, std::allocator<char>> {
    struct _Alloc_hider _field1;
};

struct less<const char *>;

struct less<std::basic_string<char>>;

struct less<unsigned long>;

struct map<const char *, MenesObjectHandle<NSString, 0>, std::less<const char *>, std::allocator<std::pair<const char *const, MenesObjectHandle<NSString, 0>>>> {
    struct _Rb_tree<const char *, std::pair<const char *const, MenesObjectHandle<NSString, 0>>, std::_Select1st<std::pair<const char *const, MenesObjectHandle<NSString, 0>>>, std::less<const char *>, std::allocator<std::pair<const char *const, MenesObjectHandle<NSString, 0>>>> _M_t;
};

struct map<unsigned long, MenesObjectHandle<Source, 0>, std::less<unsigned long>, std::allocator<std::pair<const unsigned long, MenesObjectHandle<Source, 0>>>> {
    struct _Rb_tree<unsigned long, std::pair<const unsigned long, MenesObjectHandle<Source, 0>>, std::_Select1st<std::pair<const unsigned long, MenesObjectHandle<Source, 0>>>, std::less<unsigned long>, std::allocator<std::pair<const unsigned long, MenesObjectHandle<Source, 0>>>> _M_t;
};

struct metaIndex {
    void **_field1;
    struct vector<pkgIndexFile *, std::allocator<pkgIndexFile *>> *_field2;
    char *_field3;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field4;
    struct basic_string<char, std::char_traits<char>, std::allocator<char>> _field5;
    _Bool _field6;
};

struct pair<MenesObjectHandle<NSString, 0>, MenesObjectHandle<NSString, 0>>;

struct pkgAcquire {
    void **_field1;
    struct vector<pkgAcquire::Item *, std::allocator<pkgAcquire::Item *>> _field2;
    struct Queue *_field3;
    struct Worker *_field4;
    struct MethodConfig *_field5;
    struct pkgAcquireStatus *_field6;
    unsigned long _field7;
    int _field8;
    _Bool _field9;
    _Bool _field10;
};

struct pkgAcquireStatus;

struct pkgCache;

struct pkgCacheFile {
    struct MMap *Map;
    struct pkgCache *Cache;
    struct pkgDepCache *DCache;
    struct pkgPolicy *Policy;
};

struct pkgDepCache;

struct pkgPackageManager;

struct pkgPolicy;

struct pkgProblemResolver {
    struct pkgDepCache *_field1;
    short *_field2;
    char *_field3;
    _Bool _field4;
};

struct pkgRecords {
    struct pkgCache *_field1;
    struct vector<pkgRecords::Parser *, std::allocator<pkgRecords::Parser *>> _field2;
};

struct pkgSourceList {
    struct vector<metaIndex *, std::allocator<metaIndex *>> _field1;
};

struct set<std::basic_string<char>, std::less<std::basic_string<char>>, std::allocator<std::basic_string<char>>> {
    struct _Rb_tree<std::basic_string<char>, std::basic_string<char>, std::_Identity<std::basic_string<char>>, std::less<std::basic_string<char>>, std::allocator<std::basic_string<char>>> _M_t;
};

struct timeval {
    int tv_sec;
    int tv_usec;
};

struct vector<int, std::allocator<int>> {
    struct _Vector_impl _M_impl;
};

struct vector<metaIndex *, std::allocator<metaIndex *>> {
    struct _Vector_impl _field1;
};

struct vector<pkgAcquire::Item *, std::allocator<pkgAcquire::Item *>> {
    struct _Vector_impl _field1;
};

struct vector<pkgIndexFile *, std::allocator<pkgIndexFile *>>;

struct vector<pkgRecords::Parser *, std::allocator<pkgRecords::Parser *>> {
    struct _Vector_impl _field1;
};

struct vector<std::pair<MenesObjectHandle<NSString, 0>, MenesObjectHandle<NSString, 0>>, std::allocator<std::pair<MenesObjectHandle<NSString, 0>, MenesObjectHandle<NSString, 0>>>> {
    struct _Vector_impl _M_impl;
};

typedef struct {
    unsigned long _field1;
    id *_field2;
    unsigned long *_field3;
    unsigned long _field4[5];
} CDAnonymousStruct1;

