/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

@interface CydiaLoadingView : _CC_MD5
{
    struct MenesObjectHandle<UIActivityIndicatorView, 0> spinner_;
    struct MenesObjectHandle<UILabel, 0> label_;
    struct MenesObjectHandle<UIView, 0> container_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)fp8;

@end

