/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

@interface CydiaURLProtocol : _CC_MD5
{
}

+ (id)canonicalRequestForRequest:(id)fp8;
+ (BOOL)canInitWithRequest:(id)fp8;
- (void)stopLoading;
- (void)startLoading;
- (void)_returnPNGWithImage:(id)fp8 forRequest:(id)fp12;

@end

