/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

@interface CydiaRelation : _CC_MD5
{
    struct MenesObjectHandle<NSString, 0> relationship_;
    struct MenesObjectHandle<NSMutableArray, 0> clauses_;
}

+ (BOOL)isKeyExcludedFromWebScript:(const char *)fp8;
+ (id)_attributeKeys;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)addClause:(id)fp8;
- (id)clauses;
- (id)relationship;
- (id)attributeKeys;
- (id)initWithIterator:(struct DepIterator *)fp8;

@end

