/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

@interface CydiaClause : _CC_MD5
{
    struct MenesObjectHandle<NSString, 0> package_;
    struct MenesObjectHandle<CydiaOperation, 0> version_;
}

+ (BOOL)isKeyExcludedFromWebScript:(const char *)fp8;
+ (id)_attributeKeys;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)version;
- (id)package;
- (id)attributeKeys;
- (id)initWithIterator:(struct DepIterator *)fp8;

@end

