/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol CydiaDelegate
- (void)reloadDataWithInvocation:(id)fp8;
- (void)showActionSheet:(id)fp8 fromItem:(id)fp12;
- (void)removeProgressHUD:(id)fp8;
- (id)addProgressHUD;
- (void)addTrivialSource:(id)fp8;
- (void)addSource:(id)fp8;
- (void)syncData;
- (void)_saveConfig;
- (void)updateData;
- (void)loadData;
- (void)distUpgrade;
- (_Bool)requestUpdate;
- (BOOL)updating;
- (void)beginUpdate;
- (void)removePackage:(id)fp8;
- (void)installPackages:(id)fp8;
- (void)installPackage:(id)fp8;
- (void)clearPackage:(id)fp8;
- (void)releaseNetworkActivityIndicator;
- (void)retainNetworkActivityIndicator;
- (void)saveState;
- (void)returnToCydia;
@end

