/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

@interface CyteTableViewCell : _CC_MD5
{
    struct MenesObjectHandle<CyteTableViewCellContentView, 1> content_;
    _Bool highlighted_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setSelected:(BOOL)fp8 animated:(BOOL)fp12;
- (void)_updateHighlightColorsForView:(id)fp8 highlighted:(BOOL)fp12;

@end

