/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

#import "CyteWebViewDelegate-Protocol.h"

@interface CyteWebViewTableViewCell : _CC_MD5 <CyteWebViewDelegate>
{
    struct MenesObjectHandle<CyteWebView, 1> webview_;
}

+ (id)cellWithRequest:(id)fp8;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)initWithRequest:(id)fp8;

@end

