/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CyteViewController.h"

#import "CyteWebViewDelegate-Protocol.h"
#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class NSNumber, UIScrollView;

@interface CyteWebViewController : CyteViewController <CyteWebViewDelegate, MFMailComposeViewControllerDelegate, UIWebViewDelegate>
{
    struct MenesObjectHandle<CyteWebView, 1> webview_;
    UIScrollView *scroller_;
    struct MenesObjectHandle<UIActivityIndicatorView, 0> indicator_;
    struct MenesObjectHandle<IndirectDelegate, 1> indirect_;
    struct MenesObjectHandle<NSURLAuthenticationChallenge, 0> challenge_;
    _Bool error_;
    struct MenesObjectHandle<NSURLRequest, 0> request_;
    _Bool ready_;
    NSNumber *sensitive_;
    struct MenesObjectHandle<NSURL, 0> appstore_;
    struct MenesObjectHandle<NSString, 0> title_;
    struct MenesObjectHandle<NSMutableSet, 0> loading_;
    struct MenesObjectHandle<NSMutableSet, 0> registered_;
    struct MenesObjectHandle<NSTimer, 0> timer_;
    struct MenesObjectHandle<NSObject, 0> custom_;
    struct MenesObjectHandle<NSString, 0> style_;
    struct MenesObjectHandle<WebScriptObject, 0> function_;
    float width_;
    Class class_;
    struct MenesObjectHandle<UIBarButtonItem, 0> reloaditem_;
    struct MenesObjectHandle<UIBarButtonItem, 0> loadingitem_;
    _Bool visible_;
    _Bool hidesNavigationBar_;
    _Bool allowsNavigationAction_;
}

+ (float)defaultWidth;
+ (void)_lockJavaScript:(id)fp8;
+ (void)_initialize;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)registerFrame:(id)fp8;
- (void)updateHeights:(id)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)setScrollIndicatorStyleWithName:(id)fp8;
- (void)setScrollIndicatorStyle:(int)fp8;
- (void)setScrollAlwaysBounceVerticalNumber:(id)fp8;
- (void)setScrollAlwaysBounceVertical:(_Bool)fp8;
- (void)setHidesNavigationBarByNumber:(id)fp8;
- (void)setHidesNavigationBar:(_Bool)fp8;
- (void)_setHidesNavigationBar:(_Bool)fp8 animated:(_Bool)fp12;
- (_Bool)hidesNavigationBar;
- (void)dispatchEvent:(id)fp8;
- (void)setHidesBackButtonByNumber:(id)fp8;
- (void)setHidesBackButton:(_Bool)fp8;
- (void)setBadgeValue:(id)fp8;
- (void)setNavigationBarTintColor:(id)fp8;
- (void)setNavigationBarStyle:(id)fp8;
- (void)customButtonClicked;
- (void)_customButtonClicked;
- (void)reloadButtonClicked;
- (void)callFunction:(id)fp8;
- (id)initWithRequest:(id)fp8;
- (id)initWithURL:(id)fp8;
- (id)init;
- (id)initWithWidth:(float)fp8;
- (void)releaseSubviews;
- (void)loadView;
- (id)applicationNameForUserAgent;
- (id)initWithWidth:(float)fp8 ofClass:(Class)fp12;
- (_Bool)isLoading;
- (void)_didFinishLoading;
- (void)didFinishLoading;
- (void)_didStartLoading;
- (void)didStartLoading;
- (void)applyRightButton;
- (void)layoutRightButton;
- (void)applyLoadingTitle;
- (id)rightButton;
- (void)applyLeftButton;
- (id)leftButton;
- (id)customButton;
- (int)rightButtonStyle;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)close;
- (void)webViewClose:(id)fp8;
- (_Bool)webView:(id)fp8 shouldRunJavaScriptTextInputPanelWithPrompt:(id)fp12 defaultText:(id)fp16 initiatedByFrame:(id)fp20;
- (_Bool)webView:(id)fp8 shouldRunJavaScriptConfirmPanelWithMessage:(id)fp12 initiatedByFrame:(id)fp16;
- (_Bool)webView:(id)fp8 shouldRunJavaScriptAlertPanelWithMessage:(id)fp12 initiatedByFrame:(id)fp16;
- (id)webThreadWebView:(id)fp8 resource:(id)fp12 willSendRequest:(id)fp16 redirectResponse:(id)fp20 fromDataSource:(id)fp24;
- (id)webView:(id)fp8 resource:(id)fp12 willSendRequest:(id)fp16 redirectResponse:(id)fp20 fromDataSource:(id)fp24;
- (void)webView:(id)fp8 resource:(id)fp12 didReceiveAuthenticationChallenge:(id)fp16 fromDataSource:(id)fp20;
- (void)webView:(id)fp8 didStartProvisionalLoadForFrame:(id)fp12;
- (void)webView:(id)fp8 didReceiveTitle:(id)fp12 forFrame:(id)fp16;
- (void)webView:(id)fp8 didFinishLoadForFrame:(id)fp12;
- (void)webView:(id)fp8 didFailProvisionalLoadWithError:(id)fp12 forFrame:(id)fp16;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12 forFrame:(id)fp16;
- (void)webView:(id)fp8 didCommitLoadForFrame:(id)fp12;
- (void)webView:(id)fp8 didClearWindowObject:(id)fp12 forFrame:(id)fp16;
- (void)webView:(id)fp8 decidePolicyForNewWindowAction:(id)fp12 request:(id)fp16 newFrameName:(id)fp20 decisionListener:(id)fp24;
- (void)webView:(id)fp8 didDecidePolicy:(int)fp12 forNavigationAction:(id)fp16 request:(id)fp20 frame:(id)fp24;
- (void)webView:(id)fp8 decidePolicyForNavigationAction:(id)fp12 request:(id)fp16 frame:(id)fp20 decisionListener:(id)fp24;
- (void)webView:(id)fp8 addMessageToConsole:(id)fp12;
- (void)pushRequest:(id)fp8 forAction:(id)fp12 asPop:(_Bool)fp16;
- (void)_didFailWithError:(id)fp8 forFrame:(id)fp12;
- (void)popViewControllerWithNumber:(id)fp8;
- (void)setAllowsNavigationActionByNumber:(id)fp8;
- (void)setAllowsNavigationAction:(_Bool)fp8;
- (_Bool)allowsNavigationAction;
- (_Bool)_allowJavaScriptPanel;
- (void)_openMailToURL:(id)fp8;
- (void)_setupMail:(id)fp8;
- (void)mailComposeController:(id)fp8 didFinishWithResult:(int)fp12 error:(id)fp16;
- (void)webViewUpdateViewSettings:(id)fp8;
- (void)setViewportWidthOnMainThread:(float)fp8;
- (void)_setViewportWidthOnMainThread:(id)fp8;
- (void)setViewportWidth:(float)fp8;
- (void)_setViewportWidth;
- (void)scrollToBottomAnimated:(id)fp8;
- (void)removeButton;
- (void)setButtonTitle:(id)fp8 withStyle:(id)fp12 toFunction:(id)fp16;
- (void)setButtonImage:(id)fp8 withStyle:(id)fp12 toFunction:(id)fp16;
- (void)reloadData;
- (void)reloadURLWithCache:(BOOL)fp8;
- (void)loadRequest:(id)fp8;
- (void)loadURL:(id)fp8;
- (void)loadURL:(id)fp8 cachePolicy:(unsigned int)fp12;
- (void)setURL:(id)fp8 withReferrer:(id)fp12;
- (void)setURL:(id)fp8;
- (void)setRequest:(id)fp8;
- (id)requestWithURL:(id)fp8 cachePolicy:(unsigned int)fp12 referrer:(id)fp16;
- (id)URLWithURL:(id)fp8;
- (id)webView;
- (id)description;
- (void)dealloc;
- (void)releaseNetworkActivityIndicator;
- (_Bool)retainsNetworkActivityIndicator;

@end

