/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SDURLCache.h"

@interface CYURLCache : SDURLCache
{
}

- (void)createDiskCachePath;
- (void)storeCachedResponse:(id)fp8 forRequest:(id)fp12;
- (void)logEvent:(id)fp8 forRequest:(id)fp12;

@end

