/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol FetchDelegate
- (void)stopSourceFetch:(id)fp8;
- (void)startSourceFetch:(id)fp8;
- (_Bool)isSourceCancelled;
@end

