/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CyteViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class Database;

@interface FileTable : CyteViewController <UITableViewDataSource, UITableViewDelegate>
{
    Database *database_;
    struct MenesObjectHandle<Package, 0> package_;
    struct MenesObjectHandle<NSString, 0> name_;
    struct MenesObjectHandle<NSMutableArray, 0> files_;
    struct MenesObjectHandle<UITableView, 2> list_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)reloadData;
- (void)setPackage:(id)fp8;
- (id)initWithDatabase:(id)fp8;
- (void)releaseSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (id)navigationURL;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;

@end

