/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

@interface MIMEAddress : _CC_MD5
{
    struct MenesObjectHandle<NSString, 0> name_;
    struct MenesObjectHandle<NSString, 0> address_;
}

+ (BOOL)isKeyExcludedFromWebScript:(const char *)fp8;
+ (id)_attributeKeys;
+ (id)addressWithString:(id)fp8;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithString:(id)fp8;
- (id)attributeKeys;
- (void)setAddress:(id)fp8;
- (id)address;
- (id)name;

@end

