/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CydiaWebViewController.h"

#import "ProgressDelegate-Protocol.h"

@class Database;

@interface ProgressController : CydiaWebViewController <ProgressDelegate>
{
    Database *database_;
    struct MenesObjectHandle<CydiaProgressData, 1> progress_;
    unsigned int cancel_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setProgressStatus:(id)fp8;
- (void)setProgressPercent:(id)fp8;
- (void)setProgressCancellable:(id)fp8;
- (void)setCancellable:(_Bool)fp8;
- (void)cancel;
- (_Bool)isProgressCancelled;
- (void)addProgressEvent:(id)fp8;
- (void)invoke:(id)fp8 withTitle:(id)fp12;
- (id)rightButton;
- (void)setTitle:(id)fp8;
- (void)close;
- (void)viewWillAppear:(BOOL)fp8;
- (void)updateProgress;
- (void)webView:(id)fp8 didClearWindowObject:(id)fp12 forFrame:(id)fp16;
- (id)initWithDatabase:(id)fp8 delegate:(id)fp12;
- (void)updateCancel;
- (id)leftButton;
- (void)dealloc;

@end

