/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CyteTableViewCell.h"

#import "CyteTableViewCellDelegate-Protocol.h"
#import "SourceDelegate-Protocol.h"

@interface SourceCell : CyteTableViewCell <CyteTableViewCellDelegate, SourceDelegate>
{
    struct MenesObjectHandle<Source, 1> source_;
    struct MenesObjectHandle<NSURL, 0> url_;
    struct MenesObjectHandle<UIImage, 0> icon_;
    struct MenesObjectHandle<NSString, 0> origin_;
    struct MenesObjectHandle<NSString, 0> label_;
    struct MenesObjectHandle<UIActivityIndicatorView, 0> indicator_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setFetch:(id)fp8;
- (void)drawContentRect:(struct CGRect)fp8;
- (id)accessibilityLabel;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8 reuseIdentifier:(id)fp24;
- (void)setAllSource;
- (void)setSource:(id)fp8;
- (void)_setSource:(id)fp8;
- (void)_setImage:(id)fp8;

@end

