/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_CC_MD5.h"

@class Database, NSObject<SourceDelegate>;

@interface Source : _CC_MD5
{
    unsigned int era_;
    Database *database_;
    struct metaIndex *index_;
    struct CYString depiction_;
    struct CYString description_;
    struct CYString label_;
    struct CYString origin_;
    struct CYString support_;
    struct CYString uri_;
    struct CYString distribution_;
    struct CYString type_;
    struct CYString base_;
    struct CYString version_;
    struct MenesObjectHandle<NSString, 0> host_;
    struct MenesObjectHandle<NSString, 0> authority_;
    struct CYString defaultIcon_;
    struct MenesObjectHandle<NSMutableDictionary, 0> record_;
    BOOL trusted_;
    struct set<std::basic_string<char>, std::less<std::basic_string<char>>, std::allocator<std::basic_string<char>>> fetches_;
    struct set<std::basic_string<char>, std::less<std::basic_string<char>>, std::allocator<std::basic_string<char>>> files_;
    NSObject<SourceDelegate> *delegate_;
}

+ (BOOL)isKeyExcludedFromWebScript:(const char *)fp8;
+ (id)_attributeKeys;
+ (BOOL)isSelectorExcludedFromWebScript:(SEL)fp8;
+ (id)webScriptNameForSelector:(SEL)fp8;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)resetFetch;
- (void)setFetch:(_Bool)fp8 forURI:(const char *)fp12;
- (_Bool)fetch;
- (void)setDelegate:(id)fp8;
- (id)defaultIcon;
- (id)version;
- (id)origin;
- (id)label;
- (id)shortDescription;
- (id)name;
- (id)host;
- (id)key;
- (id)iconURL;
- (id)iconuri;
- (id)baseuri;
- (id)type;
- (id)distribution;
- (id)rooturi;
- (BOOL)trusted;
- (id)record;
- (_Bool)remove;
- (void)_remove;
- (_Bool)removeSection:(id)fp8;
- (void)_removeSection:(id)fp8;
- (_Bool)addSection:(id)fp8;
- (void)_addSection:(id)fp8;
- (id)sections;
- (id)supportForPackage:(id)fp8;
- (id)depictionForPackage:(id)fp8;
- (int)compareByName:(id)fp8;
- (id)getField:(id)fp8;
- (id)initWithMetaIndex:(struct metaIndex *)fp8 forDatabase:(id)fp12 inPool:(struct CYPool *)fp16;
- (void)setMetaIndex:(struct metaIndex *)fp8 inPool:(struct CYPool *)fp12;
- (struct metaIndex *)metaIndex;
- (id)attributeKeys;

@end

