//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GSDK_GTMRegexStringSegment.h"

@interface GSDK_GTMRegexStringSegment (PrivateMethods)
- (id)initWithUTF8StrBuf:(id)arg1 regMatches:(CDStruct_912cb5d2 *)arg2 numRegMatches:(unsigned long long)arg3 isMatch:(_Bool)arg4;
@end

