//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GSDK_GTMSessionFetcherService.h"

@interface GSDK_GTMSessionFetcherService (TestingSupport)
+ (id)mockFetcherServiceWithFakedData:(id)arg1 fakedError:(id)arg2;
- (_Bool)waitForCompletionOfAllFetchersWithTimeout:(double)arg1;
@end

