//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSOperationQueue;

@interface HoloScreenShot : NSObject
{
    NSMutableArray *_paths;
    NSOperationQueue *_serial_background;
}

+ (id)instance;
- (void).cxx_destruct;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)saveScreenShot:(const char *)arg1;
- (id)init;

@end

