//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SKPaymentTransactionObserver.h"
#import "SKProductsRequestDelegate.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, SKProductsRequest;

@interface NIAInAppBillingProvider : NSObject <SKPaymentTransactionObserver, SKProductsRequestDelegate>
{
    SKProductsRequest *_productsRequest;
    NSObject<OS_dispatch_queue> *_workQueue;
    _Bool _addedObserver;
    shared_ptr_ec83ff60 _delegate;
    NSMutableDictionary *_itemToProduct;
}

+ (id)formatPrice:(id)arg1;
@property(retain) NSMutableDictionary *itemToProduct; // @synthesize itemToProduct=_itemToProduct;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (void)paymentQueue:(id)arg1 removedTransactions:(id)arg2;
- (void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
- (void)removeObserver;
- (void)addObserver;
- (id)getProductForItem:(id)arg1;
- (void)processTransactions:(id)arg1;
- (void)tryToCompleteOutstandingTransactions;
- (void)removeTransactions:(id)arg1;
- (void)finishTransaction:(id)arg1;
- (void)didProcessAppleBilling:(_Bool)arg1 transactions:(id)arg2;
- (void)completeOnePurchase:(id)arg1;
- (void)purchaseItem:(id)arg1 forUser:(id)arg2;
- (void)purchasableItems:(id)arg1;
@property(readonly) _Bool isTransactionInProgress;
@property(readonly) _Bool isBillingAvailable;
- (void)setDelegate:(const shared_ptr_ec83ff60 *)arg1;
- (void)dealloc;
- (id)initWithDelegate:(const shared_ptr_ec83ff60 *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

