//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (USBase64Encoding)
- (id)com_upsight_convertFromBase64URLToBase64EncodedString;
- (id)com_upsight_repaddedBase64URLEncodedString;
@end

