//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocationManager, NSObject<OS_dispatch_queue>, NSString;

@interface PGPIosLocationManager : NSObject <CLLocationManagerDelegate>
{
    struct LocationUpdate _locationProto;
    CLLocationManager *_locationManager;
    NSObject<OS_dispatch_queue> *_work_queue;
    struct LocationProvider *_locationProvider;
    struct LocationParameters _locationParameters;
}

@property(nonatomic) struct LocationParameters locationParameters; // @synthesize locationParameters=_locationParameters;
@property(nonatomic) struct LocationProvider *locationProvider; // @synthesize locationProvider=_locationProvider;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateHeading:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (int)requestLocationPermissions;
- (void)stop;
- (void)startUpdating;
- (void)start;
- (double)desiredAccuracy;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

