//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebView.h"

#import "WebViewProtocol.h"

@class NSString, NSURL, UIColor;

@interface UIWebView (WebViewProtocolConformed) <WebViewProtocol>
- (void)evaluateJavaScript:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)load:(id)arg1;
@property(readonly, copy, nonatomic) NSURL *URL;

// Remaining properties
@property(nonatomic) __weak id <WKUIDelegate> UIDelegate; // @dynamic UIDelegate;
@property(copy, nonatomic) UIColor *backgroundColor;
@property(readonly, nonatomic) _Bool canGoBack;
@property(readonly, nonatomic) _Bool canGoForward;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) id <UIWebViewDelegate> delegate;
@property(readonly, copy) NSString *description;
@property(nonatomic) struct CGRect frame;
@property(readonly) unsigned long long hash;
@property(nonatomic, getter=isHidden) _Bool hidden;
@property(nonatomic) __weak id <WKNavigationDelegate> navigationDelegate; // @dynamic navigationDelegate;
@property(nonatomic, getter=isOpaque) _Bool opaque;
@property(readonly) Class superclass;
@end

