//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ADBannerViewDelegate.h"
#import "UnityViewControllerListener.h"

@class ADBannerView, NSString;

@interface UnityADBanner : NSObject <ADBannerViewDelegate, UnityViewControllerListener>
{
    ADBannerView *_view;
    struct CGPoint _userLayoutCenter;
    int _bannerLayout;
    _Bool _showingBanner;
}

@property(readonly, nonatomic) _Bool adVisible; // @synthesize adVisible=_showingBanner;
@property(readonly, copy, nonatomic) ADBannerView *view; // @synthesize view=_view;
- (void).cxx_destruct;
- (void)bannerView:(id)arg1 didFailToReceiveAdWithError:(id)arg2;
- (void)bannerViewDidLoadAd:(id)arg1;
- (void)bannerViewActionDidFinish:(id)arg1;
- (_Bool)bannerViewActionShouldBegin:(id)arg1 willLeaveApplication:(_Bool)arg2;
- (void)showBanner:(_Bool)arg1;
- (void)positionForUserLayout:(struct CGPoint)arg1;
- (void)layoutBanner:(int)arg1;
- (void)interfaceDidChangeOrientation:(id)arg1;
- (void)interfaceWillChangeOrientation:(id)arg1;
- (void)dealloc;
- (id)initWithParent:(id)arg1 layout:(int)arg2;
- (id)initWithParent:(id)arg1 layout:(int)arg2 type:(int)arg3;
- (void)layoutBannerImpl;
- (float)layoutYImpl:(id)arg1;
- (float)layoutXImpl:(id)arg1;
- (void)initImpl:(id)arg1 layout:(int)arg2 type:(int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

