//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UpsightDefaults : NSObject
{
    id <UpsightDefaultsImpl> _defaultsImpl;
}

+ (id)sharedDefaults;
@property(readonly, nonatomic) id <UpsightDefaultsImpl> defaultsImpl; // @synthesize defaultsImpl=_defaultsImpl;
- (void).cxx_destruct;
- (void)removeAllDefaults;
- (void)removeDefaultForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)setBool:(_Bool)arg1 forKey:(id)arg2;
- (void)setInteger:(long long)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (_Bool)boolForKey:(id)arg1;
- (long long)integerForKey:(id)arg1;
- (id)initWithDefaultsImplementation:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

