//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSObject, NSOperationQueue, NSPredicate, NSString, UpsightStorableObject;

@protocol UpsightDataStoreInterface <NSObject>
- (NSArray *)queryObjects:(NSString *)arg1 predicate:(NSPredicate *)arg2;
- (void)removeObjects:(NSArray *)arg1 completion:(void (^)(NSError *, NSArray *))arg2;
- (void)remove:(UpsightStorableObject *)arg1 completion:(void (^)(NSError *, UpsightStorableObject *))arg2;
- (void)store:(UpsightStorableObject *)arg1 completion:(void (^)(NSError *, UpsightStorableObject *))arg2;
- (void)removeDefaultObserver:(NSObject *)arg1;
- (void)removeObserver:(NSObject *)arg1 type:(NSString *)arg2 predicate:(NSPredicate *)arg3;
- (void)removeObserver:(NSObject *)arg1 type:(NSString *)arg2;
- (void)addDefaultObserver:(NSObject *)arg1 selector:(SEL)arg2;
- (void)addObserver:(NSObject *)arg1 selector:(SEL)arg2 type:(NSString *)arg3 queue:(NSOperationQueue *)arg4 predicate:(NSPredicate *)arg5;
- (void)addObserver:(NSObject *)arg1 selector:(SEL)arg2 type:(NSString *)arg3 queue:(NSOperationQueue *)arg4;
- (void)addObserver:(NSObject *)arg1 selector:(SEL)arg2 type:(NSString *)arg3;
@end

