//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, USActionMap;

@protocol USAction <NSObject>
+ (NSString *)type;
@property(readonly, copy, nonatomic) CDUnknownBlockType handler;
@property(readonly, nonatomic) __weak USActionMap *map;
@property(readonly, nonatomic) NSDictionary *parameters;
- (void)executeWithCompletionBlock:(void (^)(void))arg1;
@end

