//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "USEvent.h"

@class NSString;

@interface USAnalyticsEvent : USEvent
{
}

+ (id)analyticsEventWithParameters:(id)arg1 name:(id)arg2;
@property(readonly, nonatomic) NSString *name;
- (id)initWithParameters:(id)arg1 name:(id)arg2;
- (id)init;
- (id)initWithType:(id)arg1 parameters:(id)arg2;

@end

