//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UpsightStorableObject.h"

@class USEvent;

@interface USBatchItem : UpsightStorableObject
{
    USEvent *_event;
}

@property(readonly, nonatomic) USEvent *event; // @synthesize event=_event;
- (void).cxx_destruct;
- (id)initWithEvent:(id)arg1;
- (id)initWithType:(id)arg1 version:(id)arg2 ID:(id)arg3;
- (id)init;

@end

