//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UpsightStorableObject.h"

@class NSDictionary, NSNumber, NSString;

@interface USConfiguration : UpsightStorableObject
{
    NSString *_configurationType;
    NSDictionary *_configurationDictionary;
    NSNumber *_sessionNumber;
}

@property(readonly, nonatomic) NSNumber *sessionNumber; // @synthesize sessionNumber=_sessionNumber;
@property(readonly, nonatomic) NSDictionary *configurationDictionary; // @synthesize configurationDictionary=_configurationDictionary;
@property(readonly, nonatomic) NSString *configurationType; // @synthesize configurationType=_configurationType;
- (void).cxx_destruct;
- (id)initWithConfigurationType:(id)arg1 configurationDictionary:(id)arg2 sessionNumber:(id)arg3;
- (id)initWithType:(id)arg1 version:(id)arg2 ID:(id)arg3;
- (id)init;

@end

