//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SKStoreProductViewControllerDelegate.h"
#import "USBillboard.h"
#import "USViewControllerDelegate.h"

@class NSString, SKStoreProductViewController;

@interface USContentUnitBillboard : NSObject <USViewControllerDelegate, SKStoreProductViewControllerDelegate, USBillboard>
{
    _Bool _presenting;
    NSString *_scope;
    id <USBillboardDelegate> _delegate;
    id <USViewController> _viewController;
    id <USContentUnitBillboardDataSource> _dataSource;
    SKStoreProductViewController *_inAppStoreController;
}

+ (id)presentingControllerToScopeMap;
@property(retain) SKStoreProductViewController *inAppStoreController; // @synthesize inAppStoreController=_inAppStoreController;
@property __weak id <USContentUnitBillboardDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(retain) id <USViewController> viewController; // @synthesize viewController=_viewController;
@property __weak id <USBillboardDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *scope; // @synthesize scope=_scope;
- (void).cxx_destruct;
- (void)executeBlockOnMainQueue:(CDUnknownBlockType)arg1 waitUntilFinished:(_Bool)arg2;
- (void)cleanupPresentingControllerToScopeMap;
- (void)onDidEnterBackground:(id)arg1;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)contentUnitViewControllerDidDismiss:(id)arg1;
- (void)contentUnitViewControllerWillDismiss:(id)arg1;
- (id)initWithScope:(id)arg1;
@property(readonly, getter=isContentReady) _Bool contentReady;
- (void)onDidReceivePurchases:(id)arg1;
- (void)onDidReceiveRewards:(id)arg1;
- (void)close;
- (void)replacePresentedControllerWithStoreUsingITunesIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)replacePresentedControllerWithViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentViewController:(id)arg1 presentingViewController:(id)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (_Bool)presentViewController:(id)arg1 animated:(_Bool)arg2;
@property(readonly, getter=isPresenting) _Bool presenting; // @synthesize presenting=_presenting;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

