//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary;

@protocol USConfigurationInterface <NSObject>
+ (NSArray *)requiredKeys;
+ (_Bool)isValidConfigurationDictionary:(NSDictionary *)arg1;
@property(readonly, nonatomic) NSDictionary *configurationDictionary;
- (id)initWithConfigurationDictionary:(NSDictionary *)arg1;
- (_Bool)isEqualToConfiguration:(id <USConfigurationInterface>)arg1;
@end

