//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "USActionMapManagerObserver.h"
#import "USBillboardManager.h"
#import "USContentUnitBillboardDataSource.h"
#import "USMediator.h"
#import "USViewControllerCacheDelegate.h"

@class NSDictionary, NSMutableArray, NSMutableDictionary, NSString, USURLLoader, USViewControllerCache;

@interface USContentUnitBillboardManager : NSObject <USViewControllerCacheDelegate, USActionMapManagerObserver, USContentUnitBillboardDataSource, USMediator, USBillboardManager>
{
    NSDictionary *_actionTypeToHandlerMap;
    USViewControllerCache *_controllersCache;
    USURLLoader *_URLLoader;
    id <UpsightDataStoreInterface> _dataStore;
    NSMutableDictionary *_scopeToBillboardMap;
    NSMutableArray *_presentScopedContentRecords;
    NSMutableDictionary *_triggerIfContentAvailableTasks;
    id <USActionMapManagerInterface> _actionMapManager;
}

@property(readonly, nonatomic) id <USActionMapManagerInterface> actionMapManager; // @synthesize actionMapManager=_actionMapManager;
@property(retain, nonatomic) NSMutableDictionary *triggerIfContentAvailableTasks; // @synthesize triggerIfContentAvailableTasks=_triggerIfContentAvailableTasks;
@property(retain, nonatomic) NSMutableArray *presentScopedContentRecords; // @synthesize presentScopedContentRecords=_presentScopedContentRecords;
@property(retain, nonatomic) NSMutableDictionary *scopeToBillboardMap; // @synthesize scopeToBillboardMap=_scopeToBillboardMap;
@property(readonly, nonatomic) id <UpsightDataStoreInterface> dataStore; // @synthesize dataStore=_dataStore;
@property(retain, nonatomic) USViewControllerCache *controllersCache; // @synthesize controllersCache=_controllersCache;
- (void).cxx_destruct;
- (CDUnknownBlockType)presentContent;
- (CDUnknownBlockType)presentDialog;
- (CDUnknownBlockType)presentScopedDialog;
- (CDUnknownBlockType)openInAppStore;
- (CDUnknownBlockType)associateOnce;
- (CDUnknownBlockType)presentCloseButton;
- (CDUnknownBlockType)sendFormData;
- (CDUnknownBlockType)openURL;
- (CDUnknownBlockType)triggerActions;
- (CDUnknownBlockType)notifyPurchases;
- (CDUnknownBlockType)notifyRewards;
- (CDUnknownBlockType)triggerIfContentAvailable;
- (CDUnknownBlockType)sendEvent;
- (CDUnknownBlockType)presentScopelessContent;
- (CDUnknownBlockType)presentScopedContent;
- (CDUnknownBlockType)buildContent;
- (id)mediatedContentUnitWithContentModel:(id)arg1;
- (id)mediatedViewController;
- (void)actionMapManager:(id)arg1 didDestroyActionMap:(id)arg2;
- (void)cache:(id)arg1 didAddController:(id)arg2;
- (_Bool)isContentAvailableForBillboard:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)findBillboardForActionMap:(id)arg1;
- (_Bool)presentViewController:(id)arg1;
@property(readonly) USURLLoader *URLLoader; // @synthesize URLLoader=_URLLoader;
@property(readonly, nonatomic) NSDictionary *actionTypeToHandlerMap; // @synthesize actionTypeToHandlerMap=_actionTypeToHandlerMap;
- (id)billboardForScope:(id)arg1;
- (void)dealloc;
- (id)initWithDataStore:(id)arg1 actionMapManager:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

