//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "USConfigurationBase.h"

@class NSArray;

@interface USDispatcherConfiguration : USConfigurationBase
{
    NSArray *_queues;
    NSArray *_routeFilters;
    NSArray *_attributeSets;
    NSArray *_attributeFilters;
}

+ (id)defaultConfiguration;
+ (id)defaultConfigurationDictionary;
+ (id)loadConfigurationDictionaryFromPlist;
+ (_Bool)isValidConfigurationDictionary:(id)arg1;
+ (_Bool)isValidArrayOfConfigurationDictionaries:(id)arg1 forClass:(Class)arg2;
@property(retain, nonatomic) NSArray *attributeFilters; // @synthesize attributeFilters=_attributeFilters;
@property(retain, nonatomic) NSArray *attributeSets; // @synthesize attributeSets=_attributeSets;
@property(retain, nonatomic) NSArray *routeFilters; // @synthesize routeFilters=_routeFilters;
@property(retain, nonatomic) NSArray *queues; // @synthesize queues=_queues;
- (void).cxx_destruct;
- (id)initWithConfigurationDictionary:(id)arg1;

@end

