//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDictionary, NSString, USSession;

@interface USEventParameters : NSObject <NSCoding>
{
    double _timestamp;
    unsigned long long _eventNumber;
    USSession *_session;
    NSString *_eventType;
    NSString *_attributeSetName;
    NSDictionary *_userAttributes;
    NSDictionary *_pubData;
    NSDictionary *_upsightData;
}

@property(copy, nonatomic) NSDictionary *upsightData; // @synthesize upsightData=_upsightData;
@property(copy, nonatomic) NSDictionary *pubData; // @synthesize pubData=_pubData;
@property(readonly, copy, nonatomic) NSDictionary *userAttributes; // @synthesize userAttributes=_userAttributes;
@property(copy, nonatomic) NSString *attributeSetName; // @synthesize attributeSetName=_attributeSetName;
@property(copy, nonatomic) NSString *eventType; // @synthesize eventType=_eventType;
@property(readonly, nonatomic) USSession *session; // @synthesize session=_session;
@property(readonly, nonatomic) unsigned long long eventNumber; // @synthesize eventNumber=_eventNumber;
@property(readonly, nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToParameters:(id)arg1;
- (unsigned long long)hash;
- (id)initWithTimestamp:(double)arg1 eventType:(id)arg2 eventNumber:(unsigned long long)arg3 session:(id)arg4 attributeSetName:(id)arg5 userAttributes:(id)arg6 pubData:(id)arg7 upsightData:(id)arg8;
- (id)init;

@end

