//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface USInstallationTracker : NSObject
{
    NSDate *_installDate;
    id <UpsightDataStoreInterface> _dataStore;
}

+ (void)migrateInstallDateIfNeeded;
@property(readonly, nonatomic) id <UpsightDataStoreInterface> dataStore; // @synthesize dataStore=_dataStore;
- (void).cxx_destruct;
@property(retain) NSDate *installDate; // @synthesize installDate=_installDate;
- (void)trackInstallation;
- (id)initWithDataStore:(id)arg1;
- (id)init;

@end

