//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface USManagedVariable : NSObject
{
    NSString *_tag;
    id _value;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (id)managedBooleanWithTag:(id)arg1;
+ (id)managedFloatWithTag:(id)arg1;
+ (id)managedIntegerWithTag:(id)arg1;
+ (id)managedStringWithTag:(id)arg1;
@property(retain, nonatomic) id value; // @synthesize value=_value;
@property(retain, nonatomic) NSString *tag; // @synthesize tag=_tag;
- (void).cxx_destruct;
- (_Bool)boolValue;
- (float)floatValue;
- (long long)integerValue;
- (id)stringValue;
- (id)initWithTag:(id)arg1 value:(id)arg2;
- (id)init;

@end

