//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@protocol USManagedVariableObserverDelegate <NSObject>

@optional
- (void)observer:(id <USManagedVariableObserver>)arg1 didSynchronizeManagedVariables:(NSArray *)arg2;
- (_Bool)observerShouldSynchronizeManagedVariables:(id <USManagedVariableObserver>)arg1;
@end

