//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface USMediatorManager : NSObject
{
    NSMutableDictionary *_providerNamesToMediatorsMap;
}

+ (id)mediatorForProviderName:(id)arg1;
+ (void)unregisterMediatorForProviderName:(id)arg1;
+ (void)registerMediator:(id)arg1 forProviderName:(id)arg2;
+ (id)sharedMediatorManager;
@property(retain, nonatomic) NSMutableDictionary *providerNamesToMediatorsMap; // @synthesize providerNamesToMediatorsMap=_providerNamesToMediatorsMap;
- (void).cxx_destruct;
- (id)mediatorForProviderName:(id)arg1;
- (void)unregisterMediatorForProviderName:(id)arg1;
- (void)registerMediator:(id)arg1 forProviderName:(id)arg2;

@end

