//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "USEvent.h"

@class NSString;

@interface USMilestoneEvent : USEvent
{
}

+ (id)milestoneEventWithParameters:(id)arg1 scope:(id)arg2;
@property(readonly, nonatomic) NSString *scope;
- (id)initWithParameters:(id)arg1 scope:(id)arg2;
- (id)initWithType:(id)arg1 parameters:(id)arg2;
- (id)init;

@end

