//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "USConfigurationBase.h"

@class NSString;

@interface USQueueConfiguration : USConfigurationBase
{
    _Bool _countNetworkFailRetries;
    NSString *_name;
    double _sendInterval;
    unsigned long long _batchSize;
    double _retryInterval;
    unsigned long long _maxRetryCount;
    NSString *_URLFormat;
    NSString *_protocol;
    NSString *_host;
}

+ (_Bool)isValidConfigurationDictionary:(id)arg1;
+ (id)requiredKeys;
+ (id)trashQueueConfigurationDictionary;
@property(retain, nonatomic) NSString *host; // @synthesize host=_host;
@property(retain, nonatomic) NSString *protocol; // @synthesize protocol=_protocol;
@property(retain, nonatomic) NSString *URLFormat; // @synthesize URLFormat=_URLFormat;
@property(nonatomic) unsigned long long maxRetryCount; // @synthesize maxRetryCount=_maxRetryCount;
@property(nonatomic) double retryInterval; // @synthesize retryInterval=_retryInterval;
@property(nonatomic) _Bool countNetworkFailRetries; // @synthesize countNetworkFailRetries=_countNetworkFailRetries;
@property(nonatomic) unsigned long long batchSize; // @synthesize batchSize=_batchSize;
@property(nonatomic) double sendInterval; // @synthesize sendInterval=_sendInterval;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithConfigurationDictionary:(id)arg1;

@end

