//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@protocol USReward <NSObject>
@property(readonly, nonatomic) NSData *signatureData;
@property(readonly, nonatomic) unsigned long long quantity;
@property(readonly, nonatomic) NSString *productIdentifier;
@end

