//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UpsightStorableObject.h"

@class NSDictionary, NSString;

@interface USResponseSection : UpsightStorableObject
{
    NSString *_sectionType;
    NSDictionary *_content;
}

@property(readonly, nonatomic) NSDictionary *content; // @synthesize content=_content;
@property(readonly, nonatomic) NSString *sectionType; // @synthesize sectionType=_sectionType;
- (void).cxx_destruct;
- (id)initWithSectionType:(id)arg1 content:(id)arg2;
- (id)initWithType:(id)arg1 version:(id)arg2 ID:(id)arg3;
- (id)init;

@end

