//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "USContentUnit.h"

@class NSDictionary, NSNumber, NSString, NSURL;

@interface USUpsightContentUnit : NSObject <USContentUnit>
{
    _Bool _fullScreen;
    NSURL *_templateURL;
    NSDictionary *_context;
    NSString *_contentProvider;
    NSNumber *_contentID;
    struct CGRect _portraitFrame;
    struct CGRect _landscapeFrame;
}

@property(readonly, nonatomic) struct CGRect landscapeFrame; // @synthesize landscapeFrame=_landscapeFrame;
@property(readonly, nonatomic) struct CGRect portraitFrame; // @synthesize portraitFrame=_portraitFrame;
@property(readonly, nonatomic) NSNumber *contentID; // @synthesize contentID=_contentID;
@property(readonly, nonatomic) NSString *contentProvider; // @synthesize contentProvider=_contentProvider;
@property(readonly, nonatomic) NSDictionary *context; // @synthesize context=_context;
@property(readonly, nonatomic) NSURL *templateURL; // @synthesize templateURL=_templateURL;
@property(readonly, nonatomic, getter=isFullScreen) _Bool fullScreen; // @synthesize fullScreen=_fullScreen;
- (void).cxx_destruct;
- (struct CGRect)frameForContainerSize:(struct CGSize)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

