//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionDelegate.h"

@class NSMutableDictionary, NSString, NSURLSession;

@interface USURLLoader : NSObject <NSURLSessionDelegate>
{
    NSURLSession *_URLSession;
    NSMutableDictionary *_dataTaskToLoaderItemMap;
}

@property(retain, nonatomic) NSMutableDictionary *dataTaskToLoaderItemMap; // @synthesize dataTaskToLoaderItemMap=_dataTaskToLoaderItemMap;
@property(retain, nonatomic) NSURLSession *URLSession; // @synthesize URLSession=_URLSession;
- (void).cxx_destruct;
- (void)openURL:(id)arg1;
- (void)completeTask:(id)arg1;
- (_Bool)isRequestWithStandardURLScheme:(id)arg1;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 task:(id)arg2 willPerformHTTPRedirection:(id)arg3 newRequest:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 didBecomeInvalidWithError:(id)arg2;
- (void)loadURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

