//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "USUXMVariableSchema.h"

@interface USUXMBooleanSchema : USUXMVariableSchema
{
}

- (_Bool)isValidValue:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

