//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class USViewControllerCache;

@protocol USViewControllerCacheDelegate <NSObject>

@optional
- (void)cache:(USViewControllerCache *)arg1 didRemoveController:(id <USViewController>)arg2;
- (void)cache:(USViewControllerCache *)arg1 didAddController:(id <USViewController>)arg2;
@end

