//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CRNetStatObserver.h"

@class CRBreadcrumbsArchive, CritterImpl;

@interface CRBreadcrumbs : NSObject <CRNetStatObserver>
{
    CRBreadcrumbsArchive *_crashedArchive;
    CRBreadcrumbsArchive *_previousArchive;
    CritterImpl *_critterDelegate;
    CRBreadcrumbsArchive *_archive;
}

+ (void)setAsyncMode:(_Bool)arg1;
+ (void)shuffleUserBreadcrumbs;
+ (id)getWindowsStyleShuffledPluginUserBreadcrumbs;
+ (id)getWindowsStyleUserBreadcrumbs;
+ (id)extractUserBreadcrumbsFrom:(double)arg1 toEndTime:(double)arg2;
+ (id)extractEndpointsFrom:(double)arg1 toEndTime:(double)arg2;
+ (id)extractAllEndpoints;
+ (id)getAllSessionsUserBreadcrumbs;
+ (void)leaveCrashBreadcrumb:(id)arg1 withReason:(id)arg2 withTimestamp:(id)arg3;
+ (void)leaveErrorBreadcrumb:(id)arg1 withReason:(id)arg2;
+ (void)leaveViewBreadcrumb:(int)arg1 withViewName:(id)arg2;
+ (void)leaveReachabilityBreadcrumb:(int)arg1 fromType:(id)arg2 toType:(id)arg3;
+ (void)leaveReachabilityBreadcrumb:(int)arg1 forType:(id)arg2;
+ (void)leaveReachabilityBreadcrumb:(int)arg1;
+ (void)leaveEventBreadcrumb:(id)arg1;
+ (void)leaveNetworkBreadcrumb:(id)arg1;
+ (void)leaveUserBreadcrumb:(id)arg1 withPriority:(int)arg2;
+ (void)leaveSessionStartBreadcrumb;
+ (id)networkBreadcrumbs;
+ (id)systemBreadcrumbs;
+ (id)userBreadcrumbs;
@property(readonly, nonatomic) CRBreadcrumbsArchive *archive; // @synthesize archive=_archive;
@property __weak CritterImpl *critterDelegate; // @synthesize critterDelegate=_critterDelegate;
@property(readonly) CRBreadcrumbsArchive *previousArchive; // @synthesize previousArchive=_previousArchive;
@property(readonly) CRBreadcrumbsArchive *crashedArchive; // @synthesize crashedArchive=_crashedArchive;
- (void).cxx_destruct;
- (id)reservedBreadcrumbs;
- (id)readFromFile;
- (void)shuffleBreadcrumbs;
- (void)logNetworkRequest:(id)arg1;
- (id)getCurrentSessionStartBreadcrumb;
- (id)getAllSessionsBreadcrumbs;
- (void)clearBreadcrumbs;
- (id)recentBreadcrumbs;
- (id)recentBreadcrumbsFrom:(double)arg1 toEndTime:(double)arg2;
- (void)leaveSessionStartBreadcrumb;
- (void)addBreadcrumb:(int)arg1 withObject:(id)arg2;
- (id)initWithName:(id)arg1 withmaxCount:(unsigned int)arg2;

@end

