//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CRCurrentConnectivity : NSObject
{
}

+ (void)setInternetConnectivity:(_Bool)arg1;
+ (void)setWifiStatus:(_Bool)arg1;
+ (long long)activeNetwork;
+ (void)reset;

@end

