//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CRDetectedClass : NSObject
{
    _Bool _isNSObjectSubclass;
    _Bool _isWebViewSubclass;
    _Bool _isViewControllerSubclass;
    NSString *_name;
}

+ (id)detectedClassWithFoundClass:(const struct cr_found_class_t *)arg1;
@property(readonly, nonatomic) _Bool isViewControllerSubclass; // @synthesize isViewControllerSubclass=_isViewControllerSubclass;
@property(readonly, nonatomic) _Bool isWebViewSubclass; // @synthesize isWebViewSubclass=_isWebViewSubclass;
@property(readonly, nonatomic) _Bool isNSObjectSubclass; // @synthesize isNSObjectSubclass=_isNSObjectSubclass;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (Class)getClass;
- (id)initWithFoundClass:(const struct cr_found_class_t *)arg1;

@end

