//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CRAppLocator, CRAppRater, CRCrashArchive, CRDevice, CRExceptionHandler, CRNetCollector, CRNetStatDispatch, CRPreferences, CRReachability, CRThrottle, CRTransactionReporter, CrittercismConfig, NSOperationQueue, NSString, PLCrashReporter;

@interface CritterImpl : NSObject
{
    id <CrittercismDelegate> delegate;
    _Bool _loggingCritterError;
    _Bool _isOptedOut;
    unsigned long long _sessionNum;
    _Bool _isReady;
    _Bool _didCrashOnLastLoad;
    _Bool _didSendAppLoadData;
    CRAppLocator *_appLocator;
    CRPreferences *_preferences;
    NSString *_deviceUUID;
    NSString *_appId;
    NSString *_critterURL;
    NSString *_netDataURL;
    NSString *_appLoadURL;
    NSString *_LibraryId;
    CRDevice *_device;
    CRExceptionHandler *_exceptionHandler;
    CRExceptionHandler *_internalExceptionHandler;
    CRCrashArchive *_crashArchive;
    CRTransactionReporter *_transactionReporter;
    CRNetStatDispatch *_netStatDispatch;
    CRNetCollector *_netCollector;
    CRAppRater *_appRater;
    CRReachability *_hostReach;
    CRReachability *_internetReach;
    CRReachability *_wifiReach;
    NSString *_lastReachabilityStatusString;
    NSOperationQueue *_breadcrumbQueue;
    CRThrottle *_pluginCrashThrottle;
    double _sessionStartTime;
    PLCrashReporter *_plCrashReporter;
    CrittercismConfig *_config;
}

+ (void)cr_logCritterError:(id)arg1;
+ (id)sharedInstance;
@property(retain) CrittercismConfig *config; // @synthesize config=_config;
@property _Bool didSendAppLoadData; // @synthesize didSendAppLoadData=_didSendAppLoadData;
@property(retain) PLCrashReporter *plCrashReporter; // @synthesize plCrashReporter=_plCrashReporter;
@property double sessionStartTime; // @synthesize sessionStartTime=_sessionStartTime;
@property(retain) CRThrottle *pluginCrashThrottle; // @synthesize pluginCrashThrottle=_pluginCrashThrottle;
@property(retain) NSOperationQueue *breadcrumbQueue; // @synthesize breadcrumbQueue=_breadcrumbQueue;
@property(copy) NSString *lastReachabilityStatusString; // @synthesize lastReachabilityStatusString=_lastReachabilityStatusString;
@property(retain) CRReachability *wifiReach; // @synthesize wifiReach=_wifiReach;
@property(retain) CRReachability *internetReach; // @synthesize internetReach=_internetReach;
@property(retain) CRReachability *hostReach; // @synthesize hostReach=_hostReach;
@property(retain) CRAppRater *appRater; // @synthesize appRater=_appRater;
@property(retain) CRNetCollector *netCollector; // @synthesize netCollector=_netCollector;
@property(retain) CRNetStatDispatch *netStatDispatch; // @synthesize netStatDispatch=_netStatDispatch;
@property(retain) CRTransactionReporter *transactionReporter; // @synthesize transactionReporter=_transactionReporter;
@property(retain) CRCrashArchive *crashArchive; // @synthesize crashArchive=_crashArchive;
@property(retain) CRExceptionHandler *internalExceptionHandler; // @synthesize internalExceptionHandler=_internalExceptionHandler;
@property(retain) CRExceptionHandler *exceptionHandler; // @synthesize exceptionHandler=_exceptionHandler;
@property(retain) CRDevice *device; // @synthesize device=_device;
@property(retain) NSString *LibraryId; // @synthesize LibraryId=_LibraryId;
@property(retain) NSString *appLoadURL; // @synthesize appLoadURL=_appLoadURL;
@property(retain) NSString *netDataURL; // @synthesize netDataURL=_netDataURL;
@property(retain) NSString *critterURL; // @synthesize critterURL=_critterURL;
@property(copy) NSString *appId; // @synthesize appId=_appId;
@property(readonly, getter=getUserUUID) NSString *deviceUUID; // @synthesize deviceUUID=_deviceUUID;
@property _Bool didCrashOnLastLoad; // @synthesize didCrashOnLastLoad=_didCrashOnLastLoad;
@property(retain) CRPreferences *preferences; // @synthesize preferences=_preferences;
@property(retain, nonatomic) CRAppLocator *appLocator; // @synthesize appLocator=_appLocator;
@property _Bool isReady; // @synthesize isReady=_isReady;
- (void).cxx_destruct;
- (void)logPluginException:(id)arg1;
- (void)setupUserVoice;
- (id)appState;
- (void)useStoredTxnSettings;
- (void)storeTxnSettings:(_Bool)arg1 withFrequency:(id)arg2 withDefaultTimeout:(double)arg3 withThresholds:(id)arg4;
- (void)configureTxnSampling:(_Bool)arg1 withFrequency:(id)arg2 withDefaultTimeout:(double)arg3 withThresholds:(id)arg4;
- (void)receivedTxnSettings:(id)arg1;
- (void)logRateMeClickWithButtonIndex:(long long)arg1;
- (void)storeAPMSettings:(_Bool)arg1 withFrequency:(id)arg2;
- (void)configureAPMSampling:(_Bool)arg1 withFrequency:(id)arg2;
- (void)useStoredAPMSettings;
- (void)receivedAPMSettings:(id)arg1;
- (void)setupNetCollectionWithCurrentDevice:(id)arg1;
- (void)setupNetMonitoringWithConfig:(id)arg1;
- (void)useStoredSettings;
- (void)parseSettings:(id)arg1 withEnabled:(_Bool *)arg2 withFrequency:(id *)arg3 andKillState:(_Bool *)arg4 persistState:(_Bool *)arg5;
- (_Bool)checkSettings:(id)arg1;
- (void)receivedSettings:(id)arg1;
- (void)handleRateMeAlert:(id)arg1;
- (void)leaveBreadcrumb:(id)arg1;
- (void)handleNotification:(id)arg1;
- (void)handleCRReachabilityNotification:(id)arg1;
- (void)handleCRReachabilityNotificationBreadcrumbs:(id)arg1;
- (void)handleUIDeviceNotification:(id)arg1;
- (void)foregroundBackgroundCheck:(id)arg1;
- (void)autoTransaction:(id)arg1 withBeginTime:(double)arg2 withEndTime:(double)arg3;
- (void)sendUserMetadata;
- (_Bool)userMetadataCacheIsDirty;
- (void)setUserMetadataCacheIsDirty:(_Bool)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)postJSONtoEndpoint:(id)arg1 withBaseURL:(id)arg2 andData:(id)arg3 andHandler:(id)arg4;
- (void)postURLEncodedToEndpoint:(id)arg1 withData:(id)arg2 andHandler:(id)arg3;
- (void)sendAppLoadData;
- (void)appLoadedWithLaunch:(_Bool)arg1;
- (id)buildRequestWithState:(int)arg1 appendUserMetadata:(_Bool)arg2;
- (id)buildAppLoadRequest;
- (void)addFullStateDataTo:(id)arg1 withDevice:(id)arg2;
- (id)getStateWithFullState:(_Bool)arg1;
- (id)makeBasicRequest;
@property(retain) id <CrittercismDelegate> delegate;
- (void)updateReachability:(id)arg1;
- (void)wifiReachabilityChanged:(id)arg1;
- (void)internetReachabilityChanged:(id)arg1;
- (void)hostReachabilityChanged:(id)arg1;
- (void)setupReachabilityUpdates;
- (void)setupAppRater;
- (void)setupNotifications;
- (void)setupNotification:(id)arg1;
- (void)setupHandledExceptions;
- (void)freeDetectedClasses;
- (void)setupURLs;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)handleCrashReportWithPLCrashReport:(id)arg1 andStoredDevice:(id)arg2 andStoredPrefs:(id)arg3 andTransactions:(id)arg4 andUserBreadcrumbs:(id)arg5 andSystemBreadcrumbs:(id)arg6 andEndpoints:(id)arg7 andPreviousVersion:(id)arg8;
- (_Bool)logNetworkRequest:(id)arg1 urlString:(id)arg2 latency:(double)arg3 bytesRead:(unsigned long long)arg4 bytesSent:(unsigned long long)arg5 responseCode:(long long)arg6 error:(id)arg7;
- (_Bool)logError:(id)arg1;
- (_Bool)logHandledException:(id)arg1;
- (void)cr_logCritterError:(id)arg1;
- (void)addFilter:(id)arg1;
- (unsigned long long)maxOfflineCrashReports;
- (void)setMaxOfflineCrashReports:(unsigned long long)arg1;
- (_Bool)getOptOutStatus;
- (void)setOptOutStatus:(_Bool)arg1;
- (void)setAsyncBreadcrumbMode:(_Bool)arg1;
- (void)enableWithAppID:(id)arg1 andConfig:(id)arg2;
- (void)enableFromConfigFile;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)dealloc;
- (void)reset;
- (id)init;

@end

