//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CritterImpl;

@interface Crittercism : NSObject
{
    CritterImpl *_critter;
}

+ (void)cr_cantFindTransaction:(id)arg1;
+ (void)resetSharedCritter;
+ (id)sharedCritter;
+ (void)logPluginException:(id)arg1;
+ (long long)loggingLevel;
+ (void)setLoggingLevel:(long long)arg1;
+ (void)setValue:(int)arg1 forTransaction:(id)arg2;
+ (void)sendAppLoadData;
+ (int)valueForTransaction:(id)arg1;
+ (void)failTransaction:(id)arg1;
+ (void)endTransaction:(id)arg1;
+ (void)cancelTransaction:(id)arg1;
+ (void)beginTransaction:(id)arg1 withValue:(int)arg2;
+ (void)beginTransaction:(id)arg1;
+ (_Bool)didCrashOnLastLoad;
+ (void)setDelegate:(id)arg1;
+ (id)delegate;
+ (void)updateLocation:(id)arg1;
+ (void)addFilter:(id)arg1;
+ (void)setValue:(id)arg1 forKey:(id)arg2;
+ (void)setUsername:(id)arg1;
+ (id)getUserUUID;
+ (void)leaveBreadcrumb:(id)arg1;
+ (void)cr_logCritterError:(id)arg1;
+ (_Bool)logError:(id)arg1;
+ (_Bool)logNetworkRequest:(id)arg1 urlString:(id)arg2 latency:(double)arg3 bytesRead:(unsigned long long)arg4 bytesSent:(unsigned long long)arg5 responseCode:(long long)arg6 error:(id)arg7;
+ (_Bool)logNetworkRequest:(id)arg1 url:(id)arg2 latency:(double)arg3 bytesRead:(unsigned long long)arg4 bytesSent:(unsigned long long)arg5 responseCode:(long long)arg6 error:(id)arg7;
+ (_Bool)logHandledException:(id)arg1;
+ (unsigned long long)maxOfflineCrashReports;
+ (void)setMaxOfflineCrashReports:(unsigned long long)arg1;
+ (_Bool)getOptOutStatus;
+ (void)setOptOutStatus:(_Bool)arg1;
+ (void)setAsyncBreadcrumbMode:(_Bool)arg1;
+ (void)enableFromConfigFile;
+ (void)enableWithAppID:(id)arg1 andConfig:(id)arg2;
+ (void)enableWithAppID:(id)arg1 andDelegate:(id)arg2 andURLFilters:(id)arg3 disableInstrumentation:(_Bool)arg4;
+ (void)enableWithAppID:(id)arg1 andURLFilters:(id)arg2;
+ (void)enableWithAppID:(id)arg1 andDelegate:(id)arg2 andURLFilters:(id)arg3;
+ (void)enableWithAppID:(id)arg1 andDelegate:(id)arg2;
+ (void)enableWithAppID:(id)arg1;
+ (void)load;
@property(nonatomic) CritterImpl *critter; // @synthesize critter=_critter;
- (void)sendAppLoadData;
- (void)logPluginException:(id)arg1;
- (void)cr_logCritterError:(id)arg1;
- (_Bool)didCrashOnLastLoad;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)addFilter:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)setUsername:(id)arg1;
- (void)leaveBreadcrumb:(id)arg1;
- (_Bool)logNetworkRequest:(id)arg1 urlString:(id)arg2 latency:(double)arg3 bytesRead:(unsigned long long)arg4 bytesSent:(unsigned long long)arg5 responseCode:(long long)arg6 error:(id)arg7;
- (_Bool)logError:(id)arg1;
- (_Bool)logHandledException:(id)arg1;
- (id)getUserUUID;
- (unsigned long long)maxOfflineCrashReports;
- (void)setMaxOfflineCrashReports:(unsigned long long)arg1;
- (_Bool)getOptOutStatus;
- (void)setOptOutStatus:(_Bool)arg1;
- (void)setAsyncBreadcrumbMode:(_Bool)arg1;
- (void)enableWithAppID:(id)arg1 andConfig:(id)arg2;
- (void)enableFromConfigFile;
- (id)init;

@end

