//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProxy.h"

#import "WCSessionDelegate.h"

@class CRNetStatDispatch, CRRequestState, NSSet, NSString;

@interface CRWCSessionDelegateProxy : NSProxy <WCSessionDelegate>
{
    id _delegate;
    NSSet *_selectorsWeRespondTo;
    CRRequestState *_reqState;
    CRNetStatDispatch *_dispatch;
}

+ (id)performSwizzledWCSessionTransferFile:(id)arg1 file:(id)arg2 metadata:(id)arg3;
+ (id)performSwizzledWCSessionTransferUserInfo:(id)arg1 userInfo:(id)arg2;
+ (id)performSwizzledWCSessionMessageData:(id)arg1 data:(id)arg2 replyHandler:(CDUnknownBlockType)arg3 errorHandler:(CDUnknownBlockType)arg4;
+ (id)performSwizzledWCSessionSendMessage:(id)arg1 message:(id)arg2 replyHandler:(CDUnknownBlockType)arg3 errorHandler:(CDUnknownBlockType)arg4;
+ (id)performSwizzledWCSessionActivateSession:(id)arg1;
+ (void)performSwizzledWCSessionSetDelegate:(id)arg1 withProxy:(id)arg2;
+ (id)performSwizzledWCSessionDelegate:(id)arg1;
+ (id)transferFileForWCSession:(id)arg1 file:(id)arg2 metadata:(id)arg3 dispatch:(id)arg4;
+ (id)transferUserInfoForWCSession:(id)arg1 userInfo:(id)arg2 dispatch:(id)arg3;
+ (void)sendMessageDataForWCSession:(id)arg1 data:(id)arg2 replyHandler:(CDUnknownBlockType)arg3 errorHandler:(CDUnknownBlockType)arg4 dispatch:(id)arg5;
+ (void)sendMessageForWCSession:(id)arg1 message:(id)arg2 replyHandler:(CDUnknownBlockType)arg3 errorHandler:(CDUnknownBlockType)arg4 dispatch:(id)arg5;
+ (void)activateSessionForWCSession:(id)arg1 dispatch:(id)arg2;
+ (void)setDelegateForWCSession:(id)arg1 delegate:(id)arg2 dispatch:(id)arg3;
+ (id)delegateForWCSession:(id)arg1 dispatch:(id)arg2;
+ (id)proxyFromSession:(id)arg1 dispatch:(id)arg2;
+ (_Bool)isInstrumented;
+ (void)uninstrumentWCSession;
+ (void)instrumentWCSessionWithDispatch:(id)arg1;
+ (void)swizzleWCSessionTransferFileWithDispatch:(id)arg1;
+ (void)swizzleWCSessionTransferUserInfoWithDispatch:(id)arg1;
+ (void)swizzleWCSessionSendMessageDataWithDispatch:(id)arg1;
+ (void)swizzleWCSessionSendMessageWithDispatch:(id)arg1;
+ (void)swizzleWCSessionActivateSessionWithDispatch:(id)arg1;
+ (void)swizzleWCSessionSetDelegateWithDispatch:(id)arg1;
+ (void)swizzleWCSessionDelegateWithDispatch:(id)arg1;
+ (void)replaceWCSessionmethod:(SEL)arg1 withSwizzledSelector:(SEL)arg2 implementedBlock:(id)arg3;
+ (_Bool)respondsToSelector:(SEL)arg1;
@property(retain, nonatomic) CRNetStatDispatch *dispatch; // @synthesize dispatch=_dispatch;
@property(retain, nonatomic) CRRequestState *reqState; // @synthesize reqState=_reqState;
@property(retain, nonatomic) NSSet *selectorsWeRespondTo; // @synthesize selectorsWeRespondTo=_selectorsWeRespondTo;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)addAssociationToSession:(id)arg1;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;
- (void)session:(id)arg1 didFinishFileTransfer:(id)arg2 error:(id)arg3;
- (void)session:(id)arg1 didReceiveFile:(id)arg2;
- (void)session:(id)arg1 didFinishUserInfoTransfer:(id)arg2 error:(id)arg3;
- (void)session:(id)arg1 didReceiveUserInfo:(id)arg2;
- (void)session:(id)arg1 didReceiveMessageData:(id)arg2 replyHandler:(CDUnknownBlockType)arg3;
- (void)session:(id)arg1 didReceiveMessageData:(id)arg2;
- (void)session:(id)arg1 didReceiveMessage:(id)arg2 replyHandler:(CDUnknownBlockType)arg3;
- (void)session:(id)arg1 didReceiveMessage:(id)arg2;
- (void)session:(id)arg1 didReceiveApplicationContext:(id)arg2;
- (id)initWithDelegate:(id)arg1 dispatch:(id)arg2;

// Remaining properties
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

