//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIWebViewDelegate.h"
#import "WKNavigationDelegate.h"
#import "WKUIDelegate.h"

@class NSString, UIView<WebViewProtocol>;

@interface CWebViewPlugin : NSObject <UIWebViewDelegate, WKUIDelegate, WKNavigationDelegate>
{
    UIView<WebViewProtocol> *webView;
    NSString *gameObjectName;
}

- (void).cxx_destruct;
- (void)goForward;
- (void)goBack;
- (_Bool)canGoForward;
- (_Bool)canGoBack;
- (void)evaluateJS:(const char *)arg1;
- (void)loadURL:(const char *)arg1;
- (void)setVisibility:(_Bool)arg1;
- (double)getScale:(id)arg1;
- (void)setMargins:(int)arg1 top:(int)arg2 right:(int)arg3 bottom:(int)arg4;
- (void)setFrame:(long long)arg1 positionY:(long long)arg2 width:(long long)arg3 height:(long long)arg4;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)dealloc;
- (id)initWithGameObjectName:(const char *)arg1 transparent:(_Bool)arg2 enableWKWebView:(_Bool)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

