//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GSDK_GTMLogger.h"

@interface GSDK_GTMLogger (GTMLoggerMacroHelpers)
- (void)logFuncAssert:(const char *)arg1 msg:(id)arg2;
- (void)logFuncError:(const char *)arg1 msg:(id)arg2;
- (void)logFuncInfo:(const char *)arg1 msg:(id)arg2;
- (void)logFuncDebug:(const char *)arg1 msg:(id)arg2;
@end

