//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GIDSignInDelegate.h"
#import "GIDSignInUIDelegate.h"
#import "SFSafariViewControllerDelegate.h"

@class GIDGoogleUser, GIDSignIn, NSString, UIViewController;

@interface NIAIosAuthenticationManager : NSObject <GIDSignInDelegate, GIDSignInUIDelegate, SFSafariViewControllerDelegate>
{
    CDUnknownBlockType _loginCompletionHandler;
    CDUnknownBlockType _logoutCompletionHandler;
    GIDGoogleUser *_signedInUser;
    _Bool _loginWithUI;
    _Bool _loginFinished;
    GIDSignIn *_signIn;
    UIViewController *_presentedViewController;
}

- (void).cxx_destruct;
- (void)signIn:(id)arg1 dismissViewController:(id)arg2;
- (void)signIn:(id)arg1 presentViewController:(id)arg2;
- (id)userEmail;
@property(readonly, copy) NSString *description;
- (id)accessToken;
- (id)authentication;
- (void)signIn:(id)arg1 didDisconnectWithUser:(id)arg2 withError:(id)arg3;
- (void)signIn:(id)arg1 didSignInForUser:(id)arg2 withError:(id)arg3;
- (void)refreshIdTokenWithCompletion:(CDUnknownBlockType)arg1;
- (void)reauthorizeUser:(CDUnknownBlockType)arg1;
- (void)performSignIn;
- (void)getAccountOrLogin:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)clearAuth:(CDUnknownBlockType)arg1;
- (int)statusForError:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

