//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ADInterstitialAdDelegate.h"
#import "UnityViewControllerListener.h"

@class ADInterstitialAd, NSString, UIViewController;

@interface UnityInterstitialAd : NSObject <ADInterstitialAdDelegate, UnityViewControllerListener>
{
    ADInterstitialAd *_interstitial;
    UIViewController *_presentController;
    _Bool _autoReload;
    _Bool _didShowAd;
}

@property(readonly, copy, nonatomic) ADInterstitialAd *interstitial; // @synthesize interstitial=_interstitial;
- (void).cxx_destruct;
- (void)viewWillAppear:(id)arg1;
- (void)viewDidDisappear:(id)arg1;
- (void)interstitialAdActionDidFinish:(id)arg1;
- (void)interstitialAdDidUnload:(id)arg1;
- (void)interstitialAdDidLoad:(id)arg1;
- (void)interstitialAd:(id)arg1 didFailWithError:(id)arg2;
- (_Bool)interstitialAdActionShouldBegin:(id)arg1 willLeaveApplication:(_Bool)arg2;
- (void)reloadAD;
- (void)show;
- (void)dealloc;
- (id)initWithController:(id)arg1 autoReload:(_Bool)arg2;
- (void)_handleReloadAD;
- (void)_loadAD;
- (void)_unloadAD;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

