//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "USBillboardDelegate.h"
#import "USManagedVariableObserverDelegate.h"

@class NSDictionary, NSMutableDictionary, NSString;

@interface UpsightManager : NSObject <USManagedVariableObserverDelegate, USBillboardDelegate>
{
    _Bool _shouldSynchronizeManagedVariables;
    NSDictionary *_remoteNotificationDictionary;
    NSMutableDictionary *_billboardDict;
}

+ (void)applicationDidBecomeActiveNotification:(id)arg1;
+ (void)applicationDidFinishLaunchingNotification:(id)arg1;
+ (id)objectFromJsonString:(id)arg1;
+ (id)jsonStringFromObject:(id)arg1;
+ (_Bool)isValidJsonObject:(id)arg1;
+ (id)sharedManger;
+ (void)load;
@property(retain, nonatomic) NSMutableDictionary *billboardDict; // @synthesize billboardDict=_billboardDict;
@property(retain, nonatomic) NSDictionary *remoteNotificationDictionary; // @synthesize remoteNotificationDictionary=_remoteNotificationDictionary;
@property(nonatomic) _Bool shouldSynchronizeManagedVariables; // @synthesize shouldSynchronizeManagedVariables=_shouldSynchronizeManagedVariables;
- (void).cxx_destruct;
- (void)observer:(id)arg1 didSynchronizeManagedVariables:(id)arg2;
- (_Bool)observerShouldSynchronizeManagedVariables:(id)arg1;
- (void)billboard:(id)arg1 didReceivePurchase:(id)arg2;
- (void)billboard:(id)arg1 didReceiveReward:(id)arg2;
- (void)billboardDidDismiss:(id)arg1;
- (void)billboardWillAppear:(id)arg1;
- (id)presentingViewControllerForBillboard:(id)arg1;
- (_Bool)isContentReadyForBillboardWithScope:(id)arg1;
- (void)destroyBillboardForScope:(id)arg1;
- (void)prepareBillboardForScope:(id)arg1;
- (void)onOpenURL:(id)arg1;
- (void)didReceiveRemoteNotification:(id)arg1;
- (void)didFailToRegisterForRemoteNotificationsWithError:(id)arg1;
- (void)didRegisterForRemoteNotificationsWithDeviceToken:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

