//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSDictionary, NSString;

@interface UpsightInternalObject : NSManagedObject
{
}

+ (id)entityDescription;

// Remaining properties
@property(copy, nonatomic) NSString *externalClassName; // @dynamic externalClassName;
@property(retain, nonatomic) NSDictionary *properties; // @dynamic properties;
@property(copy, nonatomic) NSString *type; // @dynamic type;

@end

