//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UpsightDataStoreInterface.h"

@class NSEntityDescription, NSManagedObjectContext, NSManagedObjectModel, NSMutableArray, NSMutableDictionary, NSOperationQueue, NSPersistentStoreCoordinator, NSString, NSURL;

@interface UpsightDataStore : NSObject <UpsightDataStoreInterface>
{
    NSURL *_dataStoreURL;
    NSString *_dataStoreType;
    NSEntityDescription *_entityDescription;
    NSManagedObjectModel *_objectModel;
    NSPersistentStoreCoordinator *_storeCoordinator;
    NSManagedObjectContext *_objectContext;
    NSOperationQueue *_callbackQueue;
    id _contextChangeObserver;
    NSMutableDictionary *_observers;
    NSMutableArray *_defaultObservers;
}

+ (void)removeFileAtURL:(id)arg1;
+ (_Bool)createDirectoryWithURL:(id)arg1;
+ (id)dataStoreURLWithDirectory:(id)arg1 fileNamePrefix:(id)arg2;
+ (void)removePreReleaseDataStore;
+ (id)preReleaseDefaultStore;
+ (id)defaultStore;
@property(retain, nonatomic) NSMutableArray *defaultObservers; // @synthesize defaultObservers=_defaultObservers;
@property(retain, nonatomic) NSMutableDictionary *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) id contextChangeObserver; // @synthesize contextChangeObserver=_contextChangeObserver;
@property(retain, nonatomic) NSOperationQueue *callbackQueue; // @synthesize callbackQueue=_callbackQueue;
@property(retain, nonatomic) NSManagedObjectContext *objectContext; // @synthesize objectContext=_objectContext;
@property(retain, nonatomic) NSPersistentStoreCoordinator *storeCoordinator; // @synthesize storeCoordinator=_storeCoordinator;
@property(retain, nonatomic) NSManagedObjectModel *objectModel; // @synthesize objectModel=_objectModel;
@property(retain, nonatomic) NSEntityDescription *entityDescription; // @synthesize entityDescription=_entityDescription;
@property(retain, nonatomic) NSString *dataStoreType; // @synthesize dataStoreType=_dataStoreType;
@property(retain, nonatomic) NSURL *dataStoreURL; // @synthesize dataStoreURL=_dataStoreURL;
- (void).cxx_destruct;
- (id)initWithStorageType:(id)arg1;
- (id)queryObjects:(id)arg1 predicate:(id)arg2;
- (void)removeObjects:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)remove:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)store:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)removeObserver:(id)arg1 type:(id)arg2 predicate:(id)arg3;
- (void)removeObserver:(id)arg1 type:(id)arg2;
- (void)addObserver:(id)arg1 selector:(SEL)arg2 type:(id)arg3 queue:(id)arg4 predicate:(id)arg5;
- (void)addObserver:(id)arg1 selector:(SEL)arg2 type:(id)arg3 queue:(id)arg4;
- (void)addObserver:(id)arg1 selector:(SEL)arg2 type:(id)arg3;
- (void)removeDefaultObserver:(id)arg1;
- (void)addDefaultObserver:(id)arg1 selector:(SEL)arg2 queue:(id)arg3;
- (void)addDefaultObserver:(id)arg1 selector:(SEL)arg2;
- (void)notifyObservers:(id)arg1 action:(unsigned long long)arg2;
- (void)handleContextChangeNotification:(id)arg1;
- (id)generateObjects:(id)arg1;
- (void)buildCoreDataStack;
- (void)dealloc;
- (id)initWithDataStoreURL:(id)arg1;
- (id)initWithDatabaseDirectoryURL:(id)arg1 fileNamePrefix:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

