//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UpsightStorableObject.h"

@class NSString;

@interface UpsightLogData : UpsightStorableObject
{
    NSString *_name;
    NSString *_message;
    NSString *_file;
    NSString *_function;
    long long _lineNumber;
    long long _level;
}

@property(nonatomic) long long level; // @synthesize level=_level;
@property(nonatomic) long long lineNumber; // @synthesize lineNumber=_lineNumber;
@property(retain, nonatomic) NSString *function; // @synthesize function=_function;
@property(retain, nonatomic) NSString *file; // @synthesize file=_file;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithMessage:(id)arg1 loggingLevel:(long long)arg2;
- (id)initWithType:(id)arg1 version:(id)arg2 ID:(id)arg3;
- (id)init;

@end

