//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableSet, NSSet, NSString;

@interface USActionMap : NSObject
{
    _Bool _actionMapDisposed;
    NSMutableSet *_executingActions;
    NSString *_actionFactoryType;
    NSString *_ID;
    id <USActionMapDelegate> _delegate;
    NSDictionary *_triggerToActionsMap;
    NSSet *_actionTypesIndex;
}

+ (void)registerActionHandlersWithRegistry:(id)arg1;
@property(nonatomic, getter=isActionMapDisposed) _Bool actionMapDisposed; // @synthesize actionMapDisposed=_actionMapDisposed;
@property(readonly, nonatomic) NSSet *actionTypesIndex; // @synthesize actionTypesIndex=_actionTypesIndex;
@property(readonly, nonatomic) NSDictionary *triggerToActionsMap; // @synthesize triggerToActionsMap=_triggerToActionsMap;
@property(nonatomic) __weak id <USActionMapDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSString *ID; // @synthesize ID=_ID;
@property(readonly, nonatomic) NSString *actionFactoryType; // @synthesize actionFactoryType=_actionFactoryType;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSMutableSet *executingActions; // @synthesize executingActions=_executingActions;
- (void)onActionMapDidFinishExecution;
- (void)onDisposeActionCalled;
- (_Bool)containsActionsWithType:(id)arg1;
- (void)executeActionsForTrigger:(id)arg1;
- (id)initWithActionMapDictionary:(id)arg1 factory:(id)arg2;
- (id)init;

@end

