//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class USEventDataAssociationMap;

@interface USAssociationDataProvider : NSObject
{
    USEventDataAssociationMap *_oneTimeAssociationMap;
}

+ (id)sharedProvider;
@property(retain, nonatomic) USEventDataAssociationMap *oneTimeAssociationMap; // @synthesize oneTimeAssociationMap=_oneTimeAssociationMap;
- (void).cxx_destruct;
- (void)addOneTimeAssociation:(id)arg1;
- (id)obtainAndRemoveAssociatedUpsightDataForEventType:(id)arg1 upsightData:(id)arg2;
- (id)initWithAssociationMap:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

