//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "USConfigurationBase.h"

@class NSArray, NSString;

@interface USAttributeSet : USConfigurationBase
{
    NSArray *_excludes;
    NSArray *_includes;
    NSString *_name;
}

+ (_Bool)isValidConfigurationDictionary:(id)arg1;
+ (id)requiredKeys;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSArray *includes; // @synthesize includes=_includes;
@property(retain, nonatomic) NSArray *excludes; // @synthesize excludes=_excludes;
- (void).cxx_destruct;
- (id)initWithConfigurationDictionary:(id)arg1;

@end

