//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "USEvent.h"

@class NSString;

@interface USAttributionEvent : USEvent
{
}

+ (id)attributionEventWithParameters:(id)arg1 campaign:(id)arg2 creative:(id)arg3 source:(id)arg4;
@property(readonly, nonatomic) NSString *source;
@property(readonly, nonatomic) NSString *creative;
@property(readonly, nonatomic) NSString *campaign;
- (id)initWithParameters:(id)arg1 campaign:(id)arg2 creative:(id)arg3 source:(id)arg4;
- (id)initWithType:(id)arg1 parameters:(id)arg2;
- (id)init;

@end

