//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "USAction.h"

@class NSDictionary, NSString, USActionMap;

@interface USBaseAction : NSObject <USAction>
{
    NSDictionary *_parameters;
    USActionMap *_map;
    CDUnknownBlockType _handler;
}

+ (id)type;
@property(readonly, copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(readonly, nonatomic) __weak USActionMap *map; // @synthesize map=_map;
@property(readonly, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
- (void).cxx_destruct;
- (void)executeWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)initWithParameters:(id)arg1 map:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

