//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol USBillboard <NSObject>
@property(readonly, getter=isContentReady) _Bool contentReady;
@property __weak id <USBillboardDelegate> delegate;
@property(readonly, getter=isPresenting) _Bool presenting;
@property(readonly, copy) NSString *scope;
@end

