//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController;

@protocol USBillboardDelegate <NSObject>
- (UIViewController *)presentingViewControllerForBillboard:(id <USBillboard>)arg1;

@optional
- (void)billboard:(id <USBillboard>)arg1 didReceivePurchase:(id <USPurchase>)arg2;
- (void)billboard:(id <USBillboard>)arg1 didReceiveReward:(id <USReward>)arg2;
- (void)billboardDidDismiss:(id <USBillboard>)arg1;
- (void)billboardWillDismiss:(id <USBillboard>)arg1;
- (void)billboardDidAppear:(id <USBillboard>)arg1;
- (void)billboardWillAppear:(id <USBillboard>)arg1;
@end

