//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface USCrypto : NSObject
{
}

+ (id)MD5ForData:(id)arg1;
+ (id)SHA1ForData:(id)arg1;
+ (id)SHA256ForData:(id)arg1;
+ (id)SHA512ForData:(id)arg1;

@end

