//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSData, NSError;

@protocol USDeliveryQueueDelegate <NSObject>
- (void)deliveryQueue:(id <USDeliveryQueueInterface>)arg1 didFailPacketsDelivery:(NSArray *)arg2 error:(NSError *)arg3;
- (void)deliveryQueue:(id <USDeliveryQueueInterface>)arg1 didDeliverPackets:(NSArray *)arg2 response:(NSData *)arg3;
@end

