//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "USBatcherDelegate.h"
#import "USDeliveryQueueInterface.h"

@class NSMutableDictionary, NSOperationQueue, NSString, USQueueConfiguration, USRequestAttributeSetBuilder;

@interface USDeliveryQueue : NSObject <USBatcherDelegate, USDeliveryQueueInterface>
{
    id <USDeliveryQueueDelegate> _delegate;
    USQueueConfiguration *_queueConfiguration;
    USRequestAttributeSetBuilder *_attributeBuilder;
    id <USDataSenderInterface> _dataSender;
    NSMutableDictionary *_attributeSetNameToBatcher;
    NSMutableDictionary *_eventIdToPacket;
    NSOperationQueue *_operationQueue;
}

@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain, nonatomic) NSMutableDictionary *eventIdToPacket; // @synthesize eventIdToPacket=_eventIdToPacket;
@property(retain, nonatomic) NSMutableDictionary *attributeSetNameToBatcher; // @synthesize attributeSetNameToBatcher=_attributeSetNameToBatcher;
@property(retain, nonatomic) id <USDataSenderInterface> dataSender; // @synthesize dataSender=_dataSender;
@property(retain, nonatomic) USRequestAttributeSetBuilder *attributeBuilder; // @synthesize attributeBuilder=_attributeBuilder;
@property(retain, nonatomic) USQueueConfiguration *queueConfiguration; // @synthesize queueConfiguration=_queueConfiguration;
@property(nonatomic) __weak id <USDeliveryQueueDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)batcher:(id)arg1 didFailEventsDelivery:(id)arg2 error:(id)arg3;
- (void)batcher:(id)arg1 didDeliverEvents:(id)arg2 response:(id)arg3;
- (void)drain;
- (id)packetsForEventIDs:(id)arg1;
- (id)eventIDsFromEvents:(id)arg1;
- (void)enqueuePacket:(id)arg1;
@property(readonly, nonatomic) NSString *name;
- (id)initWithQueueConfiguration:(id)arg1 attributeBuilder:(id)arg2 operationQueue:(id)arg3 dataSender:(id)arg4;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

