//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "USModifyValueOperation.h"

@interface USDecrementValueOperation : USModifyValueOperation
{
}

+ (id)operatorName;
- (id)valueByPerformingOperationWithObject:(id)arg1 error:(id *)arg2;
- (id)initWithPropertyName:(id)arg1 propertyValue:(id)arg2;

@end

