//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface USEventBatch : NSObject
{
    NSMutableArray *_itemsArray;
    unsigned long long _batchSize;
}

@property(readonly, nonatomic) unsigned long long batchSize; // @synthesize batchSize=_batchSize;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSMutableArray *itemsArray; // @synthesize itemsArray=_itemsArray;
@property(readonly, nonatomic) NSArray *items;
- (void)addEventsFromArray:(id)arg1;
- (void)addEvent:(id)arg1;
- (id)dictionaryRepresentationWithBatchParameters:(id)arg1;
@property(readonly, nonatomic, getter=isFull) _Bool full;
- (id)initWithBatchSize:(unsigned long long)arg1;

@end

