//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSData, NSError, USEventRouter;

@protocol USEventRouterDelegate <NSObject>
- (void)eventRouterDidDrain:(USEventRouter *)arg1;
- (void)eventRouter:(USEventRouter *)arg1 didFailWithError:(NSError *)arg2 items:(NSArray *)arg3;
- (void)eventRouter:(USEventRouter *)arg1 didDeliverItems:(NSArray *)arg2 response:(NSData *)arg3;
@end

