//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface USEventDataAssociationMap : NSObject
{
    NSMutableDictionary *_typeToAssociationsMap;
    id <UpsightDataStoreInterface> _dataStore;
    double _expirationInterval;
}

@property(readonly, nonatomic) double expirationInterval; // @synthesize expirationInterval=_expirationInterval;
@property(readonly, nonatomic) id <UpsightDataStoreInterface> dataStore; // @synthesize dataStore=_dataStore;
- (void).cxx_destruct;
- (_Bool)isStorableExpired:(id)arg1;
- (void)removeCachedStorables:(id)arg1;
- (void)cacheStorables:(id)arg1;
- (void)filterStorables:(id)arg1 expired:(id *)arg2 valid:(id *)arg3;
- (void)loadAndCacheAssociationStorables;
@property(readonly, nonatomic) NSMutableDictionary *typeToAssociationsMap; // @synthesize typeToAssociationsMap=_typeToAssociationsMap;
- (id)associationsForEventType:(id)arg1;
- (void)removeAssociation:(id)arg1;
- (void)addAssociation:(id)arg1;
- (id)init;
- (id)initWithDataStore:(id)arg1 expirationInterval:(double)arg2;

@end

