//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "USMediator.h"
#import "USPartner.h"

@class NSDictionary, NSNumber, NSString, NSTimer;

@interface USFusePartner : NSObject <USPartner, USMediator>
{
    _Bool _isInitialized;
    _Bool _isPresent;
    NSString *_version;
    unsigned long long _state;
    id _fuseAPI;
    NSString *_fuseToken;
    NSNumber *_partnerID;
    NSDictionary *_currentConfiguration;
    NSNumber *_maxRetries;
    NSNumber *_retryCount;
    NSTimer *_preloadTimer;
    NSString *_platform;
    CDUnknownBlockType _startCallback;
    CDUnknownBlockType _preloadCallback;
    CDUnknownBlockType _shownCallback;
    CDUnknownBlockType _clickedCallback;
    CDUnknownBlockType _closedCallback;
    CDUnknownBlockType _completeCallback;
}

+ (id)partnerName;
@property(copy, nonatomic) CDUnknownBlockType completeCallback; // @synthesize completeCallback=_completeCallback;
@property(copy, nonatomic) CDUnknownBlockType closedCallback; // @synthesize closedCallback=_closedCallback;
@property(copy, nonatomic) CDUnknownBlockType clickedCallback; // @synthesize clickedCallback=_clickedCallback;
@property(copy, nonatomic) CDUnknownBlockType shownCallback; // @synthesize shownCallback=_shownCallback;
@property(copy, nonatomic) CDUnknownBlockType preloadCallback; // @synthesize preloadCallback=_preloadCallback;
@property(copy, nonatomic) CDUnknownBlockType startCallback; // @synthesize startCallback=_startCallback;
@property(retain, nonatomic) NSString *platform; // @synthesize platform=_platform;
@property(retain, nonatomic) NSTimer *preloadTimer; // @synthesize preloadTimer=_preloadTimer;
@property(retain, nonatomic) NSNumber *retryCount; // @synthesize retryCount=_retryCount;
@property(retain, nonatomic) NSNumber *maxRetries; // @synthesize maxRetries=_maxRetries;
@property(retain, nonatomic) NSDictionary *currentConfiguration; // @synthesize currentConfiguration=_currentConfiguration;
@property(retain, nonatomic) NSNumber *partnerID; // @synthesize partnerID=_partnerID;
@property(retain, nonatomic) NSString *fuseToken; // @synthesize fuseToken=_fuseToken;
@property(retain, nonatomic) id fuseAPI; // @synthesize fuseAPI=_fuseAPI;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
- (void).cxx_destruct;
- (void)callStartCallbackWithResult:(_Bool)arg1 error:(id)arg2;
- (void)handlePreloadTimeout:(id)arg1;
- (void)removePreloadTimer;
- (id)partnerInfo;
@property(readonly, nonatomic) NSString *version; // @synthesize version=_version;
@property(readonly, nonatomic) _Bool isPresent; // @synthesize isPresent=_isPresent;
- (void)fuseAdClicked;
- (void)rewardedAdCompleteWithObject:(id)arg1;
- (void)adWillClose;
- (void)adFailedToDisplay;
- (void)adDidShow:(id)arg1 mediaType:(id)arg2;
- (void)adAvailabilityResponse:(id)arg1 Error:(id)arg2;
- (void)retryStartSession;
- (void)sessionLoginError:(id)arg1;
- (void)sessionStartReceived;
- (id)mediatedContentUnitWithContentModel:(id)arg1;
- (id)mediatedViewController;
- (void)clearCallbacks;
- (void)showAdForZone:(id)arg1 adShown:(CDUnknownBlockType)arg2 adClicked:(CDUnknownBlockType)arg3 adClosed:(CDUnknownBlockType)arg4 adCompleted:(CDUnknownBlockType)arg5;
- (void)preloadAdForZone:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)startFuseSession:(id)arg1;
- (void)startWithPartnerID:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)transitionToState:(unsigned long long)arg1;
@property(readonly, nonatomic) _Bool isInitialized; // @synthesize isInitialized=_isInitialized;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

