//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "USPurchaseInfo.h"

@class NSDictionary, NSString;

@interface USInAppPurchaseInfo : USPurchaseInfo
{
    NSString *_transactionIdentifier;
    NSDictionary *_IAPBundle;
}

+ (id)IAPInfoWithResolution:(unsigned long long)arg1 currency:(id)arg2 quantity:(unsigned long long)arg3 product:(id)arg4 price:(float)arg5 transactionIdentifier:(id)arg6;
@property(retain, nonatomic) NSDictionary *IAPBundle; // @synthesize IAPBundle=_IAPBundle;
@property(readonly, nonatomic) NSString *transactionIdentifier; // @synthesize transactionIdentifier=_transactionIdentifier;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (id)initWithResolution:(unsigned long long)arg1 currency:(id)arg2 quantity:(unsigned long long)arg3 product:(id)arg4 price:(float)arg5 transactionIdentifier:(id)arg6;
- (id)initWithResolution:(unsigned long long)arg1 totalPrice:(float)arg2 currency:(id)arg3 quantity:(unsigned long long)arg4 product:(id)arg5 price:(float)arg6;

// Remaining properties
@property(retain, nonatomic) NSString *currency; // @dynamic currency;
@property(nonatomic) float price; // @dynamic price;
@property(readonly, nonatomic) NSString *product; // @dynamic product;
@property(readonly, nonatomic) unsigned long long quantity; // @dynamic quantity;
@property(readonly, nonatomic) unsigned long long resolution; // @dynamic resolution;
@property(nonatomic) float totalPrice; // @dynamic totalPrice;

@end

