//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class CLLocation;

@interface USLocation : NSObject <NSCoding, NSCopying>
{
    CLLocation *_coreLocation;
    unsigned long long _validForSessionWithNumber;
}

@property(nonatomic) unsigned long long validForSessionWithNumber; // @synthesize validForSessionWithNumber=_validForSessionWithNumber;
@property(readonly, nonatomic) CLLocation *coreLocation; // @synthesize coreLocation=_coreLocation;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic, getter=isValid) _Bool valid;
- (id)initWithCoreLocation:(id)arg1;
- (id)init;

@end

