//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "USEvent.h"

@class USMonetizationPurchaseInfo;

@interface USMonetizationEvent : USEvent
{
    USMonetizationPurchaseInfo *_info;
}

+ (id)monetizationEventWithWithParameters:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) USMonetizationPurchaseInfo *info; // @synthesize info=_info;
- (void).cxx_destruct;
- (id)initWithParameters:(id)arg1 monetizationInfo:(id)arg2;
- (id)initWithType:(id)arg1 parameters:(id)arg2;
- (id)init;

@end

