//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface USModifyValueOperationFactory : NSObject
{
}

+ (id)operatorToClassMap;
+ (id)operationWithPropertyName:(id)arg1 propertyValue:(id)arg2 operator:(id)arg3;

@end

