//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"
#import "USPartnerInfoProvider.h"

@class NSDictionary, NSNumber, NSString;

@protocol USPartner <NSObject, USPartnerInfoProvider>
+ (NSString *)partnerName;
@property(readonly, nonatomic) NSString *version;
@property(readonly, nonatomic) _Bool isInitialized;
@property(readonly, nonatomic) _Bool isPresent;
- (void)startWithPartnerID:(NSNumber *)arg1 configuration:(NSDictionary *)arg2 completion:(void (^)(_Bool, NSError *))arg3;
@end

