//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "USEvent.h"

@class NSString;

@interface USPushRegistrationEvent : USEvent
{
}

+ (id)eventWithParameters:(id)arg1 token:(id)arg2;
@property(readonly, nonatomic) NSString *token;
- (_Bool)shouldRegisterToken:(id)arg1 withTTL:(double)arg2;
- (id)initWithParameters:(id)arg1 token:(id)arg2;
- (id)initWithType:(id)arg1 parameters:(id)arg2;

@end

