//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDictionary, NSString;

@interface USPurchaseInfo : NSObject <NSCoding>
{
    float _price;
    float _totalPrice;
    unsigned long long _resolution;
    NSString *_product;
    unsigned long long _quantity;
    NSString *_currency;
}

+ (id)resolutionMap;
@property(nonatomic) float totalPrice; // @synthesize totalPrice=_totalPrice;
@property(nonatomic) float price; // @synthesize price=_price;
@property(retain, nonatomic) NSString *currency; // @synthesize currency=_currency;
@property(nonatomic) unsigned long long quantity; // @synthesize quantity=_quantity;
@property(retain, nonatomic) NSString *product; // @synthesize product=_product;
@property(nonatomic) unsigned long long resolution; // @synthesize resolution=_resolution;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (id)initWithResolution:(unsigned long long)arg1 totalPrice:(float)arg2 currency:(id)arg3 quantity:(unsigned long long)arg4 product:(id)arg5 price:(float)arg6;
- (id)init;

@end

