//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class USActionMapManager, USAnalytics, USConfigurationManager, USContentUnitBillboardManager, USDispatcher, USPartnerManager;

@interface USServices : NSObject
{
    id <UpsightDataStoreInterface> _dataStore;
    USAnalytics *_analytics;
    USDispatcher *_dispatcher;
    USConfigurationManager *_configManager;
    USActionMapManager *_actionMapManager;
    USPartnerManager *_partnerManager;
    USContentUnitBillboardManager *_billboardManager;
}

@property(retain, nonatomic) USContentUnitBillboardManager *billboardManager; // @synthesize billboardManager=_billboardManager;
@property(retain, nonatomic) USPartnerManager *partnerManager; // @synthesize partnerManager=_partnerManager;
@property(retain, nonatomic) USActionMapManager *actionMapManager; // @synthesize actionMapManager=_actionMapManager;
@property(retain, nonatomic) USConfigurationManager *configManager; // @synthesize configManager=_configManager;
@property(retain, nonatomic) USDispatcher *dispatcher; // @synthesize dispatcher=_dispatcher;
@property(retain, nonatomic) USAnalytics *analytics; // @synthesize analytics=_analytics;
@property(nonatomic) __weak id <UpsightDataStoreInterface> dataStore; // @synthesize dataStore=_dataStore;
- (void).cxx_destruct;

@end

