//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, USInstallationTracker;

@interface USServiceManager : NSObject
{
    _Bool _initialized;
    NSMutableSet *_services;
    USInstallationTracker *_installationTracker;
}

+ (id)installationTracker;
+ (id)actionMapManagerForStore:(id)arg1;
+ (id)billboardManagerForStore:(id)arg1;
+ (id)analyticsForStore:(id)arg1;
+ (void)load;
+ (id)sharedServiceManager;
@property(retain, nonatomic) USInstallationTracker *installationTracker; // @synthesize installationTracker=_installationTracker;
@property(retain, nonatomic) NSMutableSet *services; // @synthesize services=_services;
@property(nonatomic) _Bool initialized; // @synthesize initialized=_initialized;
- (void).cxx_destruct;
- (void)initializeSDK;
- (void)onApplicationDidFinishLaunching:(id)arg1;
- (void)installObservers;
- (id)partnerManagerForStore:(id)arg1;
- (id)actionMapManagerForStore:(id)arg1;
- (id)billboardManagerForStore:(id)arg1;
- (id)configurationManagerForStore:(id)arg1;
- (id)analyticsForStore:(id)arg1;
- (id)dispatcherForStore:(id)arg1;
- (id)servicesForDataStore:(id)arg1;
- (void)stopServicesWithStore:(id)arg1;
- (void)startServicesWithStore:(id)arg1;
- (void)dealloc;
- (id)init;

@end

