//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSNumber;

@interface USSession : NSObject <NSCoding, NSCopying>
{
    double _startTime;
    double _sessionDuration;
    double _previousSessionsDuration;
    unsigned long long _sessionNumber;
    NSNumber *_messageID;
    NSNumber *_campaignID;
}

@property(retain, nonatomic) NSNumber *campaignID; // @synthesize campaignID=_campaignID;
@property(retain, nonatomic) NSNumber *messageID; // @synthesize messageID=_messageID;
@property(nonatomic) unsigned long long sessionNumber; // @synthesize sessionNumber=_sessionNumber;
@property(nonatomic) double previousSessionsDuration; // @synthesize previousSessionsDuration=_previousSessionsDuration;
@property(nonatomic) double sessionDuration; // @synthesize sessionDuration=_sessionDuration;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqualToSession:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithStartTime:(double)arg1 sessionDuration:(double)arg2 previousSessionsDuration:(double)arg3 sessionNumber:(unsigned long long)arg4 messageID:(id)arg5 campaignID:(id)arg6;
- (id)init;

@end

