//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface USSIDProvider : NSObject
{
}

+ (void)migrateSIDFromStoreIfNeeded:(id)arg1;
+ (id)SID;
+ (void)removeSID;
+ (id)loadSID;
+ (id)generateSID;

@end

