//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL, NSURLConnection;

@interface USURLLoaderItem : NSObject
{
    NSURLConnection *_connection;
    NSURL *_resultingURL;
    unsigned long long _numberOfRedirects;
}

@property(nonatomic) unsigned long long numberOfRedirects; // @synthesize numberOfRedirects=_numberOfRedirects;
@property(retain, nonatomic) NSURL *resultingURL; // @synthesize resultingURL=_resultingURL;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
- (void).cxx_destruct;

@end

