//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UpsightDefaultsImpl.h"

@class NSString;

@interface USUserDefaultsBasedDefaultsImpl : NSObject <UpsightDefaultsImpl>
{
}

- (void)removeAllDefaults;
- (void)setDefault:(id)arg1 forKey:(id)arg2;
- (id)defaultForKey:(id)arg1;
- (void)removeDefaultForKey:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

