//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface USUXMVariableSchema : NSObject
{
    id _defaultValue;
    NSString *_type;
    NSString *_tag;
    NSString *_variableDescription;
}

@property(readonly, nonatomic) NSString *variableDescription; // @synthesize variableDescription=_variableDescription;
@property(readonly, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(readonly, nonatomic) NSString *type; // @synthesize type=_type;
@property(readonly, nonatomic) id defaultValue; // @synthesize defaultValue=_defaultValue;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;
- (_Bool)isValidValue:(id)arg1;
- (id)init;
- (id)initWithDictionary:(id)arg1;

@end

