//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL, NSURLRequest, UIColor;

@protocol WebViewProtocol <NSObject>
@property(readonly, nonatomic) _Bool canGoForward;
@property(readonly, nonatomic) _Bool canGoBack;
@property(readonly, copy, nonatomic) NSURL *URL;
@property(nonatomic) __weak id <WKUIDelegate> UIDelegate;
@property(nonatomic) __weak id <WKNavigationDelegate> navigationDelegate;
@property(nonatomic) id <UIWebViewDelegate> delegate;
@property(nonatomic) struct CGRect frame;
@property(nonatomic, getter=isHidden) _Bool hidden;
@property(copy, nonatomic) UIColor *backgroundColor;
@property(nonatomic, getter=isOpaque) _Bool opaque;
- (void)goForward;
- (void)goBack;
- (void)evaluateJavaScript:(NSString *)arg1 completionHandler:(void (^)(id, NSError *))arg2;
- (void)load:(NSURLRequest *)arg1;
@end

